{
  "hash": "69b19cd9df4c5519fe945642c0cd1eac",
  "result": {
    "engine": "knitr",
    "markdown": "# Linear models and t-tests {#sec-linear}\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nIn the last chapter we analyzed Darwin’s maize data and computed confidence intervals “by hand.” That helped build intuition about estimates, standard errors, and confidence. Here, we’ll move to faster, standard tools:\n\n- `rstatix::t_test()` for two-sample t-tests (Welch and equal-variance/Student).\n- `lm()` for linear models (which also reproduces the two-sample t-test).\n- `lm()` with `sandwich` (robust) standard errors to guard against unequal variances.\n\n### Packages\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(here)\nlibrary(rstatix)     # simple t-tests with tidy output\nlibrary(broom)       # tidy model summaries (optional)\nlibrary(sandwich)    # robust (heteroskedasticity-consistent) variance estimators\nlibrary(lmtest)      # coeftest/coefci for robust inference\nlibrary(performance) # easy model checks\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n## Quick start: two-sample t-tests with rstatix\n\nThe function `rstatix::t_test()` conducts a two-sample t-test from a simple formula: `outcome ~ group`.\n\n- Welch’s t-test (default; does not assume equal variances)\n\n- Student’s t-test (set `var.equal = TRUE` to assume equal variances)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Welch's t-test (default and recommended when in doubt)\ndarwin |> \n  t_test(height ~ type, detailed = TRUE)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| estimate| estimate1| estimate2|.y.    |group1 |group2 | n1| n2| statistic|      p|       df|  conf.low| conf.high|method |alternative |\n|--------:|---------:|---------:|:------|:------|:------|--:|--:|---------:|------:|--------:|---------:|---------:|:------|:-----------|\n| 2.616667|  20.19167|    17.575|height |Cross  |Self   | 15| 15|  2.437113| 0.0233| 22.16409| 0.3909566|  4.842377|T-test |two.sided   |\n\n</div>\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Equal-variance (Student's) t-test\ndarwin |>\n  t_test(height ~ type, var.equal = TRUE, detailed = TRUE)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| estimate| estimate1| estimate2|.y.    |group1 |group2 | n1| n2| statistic|      p| df|  conf.low| conf.high|method |alternative |\n|--------:|---------:|---------:|:------|:------|:------|--:|--:|---------:|------:|--:|---------:|---------:|:------|:-----------|\n| 2.616667|  20.19167|    17.575|height |Cross  |Self   | 15| 15|  2.437113| 0.0214| 28| 0.4173433|   4.81599|T-test |two.sided   |\n\n</div>\n:::\n:::\n\n\nThe core outputs are:\n\n- estimate: the difference in means (reference group is the first level in alphabetical order unless otherwise set)\n\n- conf.low, conf.high: 95% confidence interval\n\n- statistic, df, p: t-value, degrees of freedom, and p-value\n\nYou can also quickly see group summaries:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndarwin |> \n  group_by(type) |>\n  summarise(\n    n = n(),\n    mean = mean(height),\n    sd = sd(height),\n    se = sd/sqrt(n)\n  )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|type  |  n|     mean|       sd|        se|\n|:-----|--:|--------:|--------:|---------:|\n|Cross | 15| 20.19167| 3.616945| 0.9338912|\n|Self  | 15| 17.57500| 2.051676| 0.5297405|\n\n</div>\n:::\n:::\n\n\n::: {.callout-tip}\nWhich t-test should I use?\n- Start with Welch (default), as it is robust to unequal variances.\n- If you have good reason (and checks) to assume equal variances, use `var.equal = TRUE`.\n:::\n\n::: {.callout-note}\nOptional: Check equal variances\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# A simple variance homogeneity check (Levene test).\n# If p is small (e.g., < 0.05), variances are likely unequal.\nrstatix::levene_test(darwin, height ~ type)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| df1| df2| statistic|         p|\n|---:|---:|---------:|---------:|\n|   1|  28| 0.7686161| 0.3881056|\n\n</div>\n:::\n:::\n\n:::\n\n\n:::{.callout-note collapse=\"true\"}\n# What is variance?\n\nVariance is a statistical measure of how spread out or dispersed a dataset is from its mean. Student vs Welch's t use two different calculations that either \"pool\" or keep sd separate when comparing group means:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09-linear-models_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n## A linear model (lm) approach\n\nA two-sample t-test is a special case of a linear model. With `lm(height ~ type)`, the coefficient for the non-reference level represents the difference in means. Most of the common statistical models (t-test, correlation, ANOVA; chi-square, etc.) are special cases of linear models or a very close approximation. This beautiful simplicity means that there is less to learn: \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlsmodel1 <- lm(height ~ type, data = darwin)\n```\n:::\n\n\n:::{callout-note}\nThe linear-model uses a technique called [least squares](https://www.youtube.com/watch?v=PaFPbb66DxQ). \n:::\n\n:::{.callout-tip}\nYou can pipe into the lm() function, but when we use functions that are \"outside\" of the tidyverse family we need to put a `_` where the data should go (as it is usually not the first argument).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlsmodel1 <- darwin |> \n             lm(height ~ type, data= _)\n```\n:::\n\n\n:::\n\n## Summaries for models\n\nWhen you have made a linear model, we can investigate a summary of the model using the base R function `summary()`. There is also a tidyverse option provided by the package `broom`(@R-broom).\n\n::: {.panel-tabset}\n\n## Base R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Base R summary (includes estimates, SE, t, p)\nsummary(lsmodel1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = height ~ type, data = darwin)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8.1917 -1.0729  0.8042  1.9021  3.3083 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  20.1917     0.7592  26.596   <2e-16 ***\ntypeSelf     -2.6167     1.0737  -2.437   0.0214 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.94 on 28 degrees of freedom\nMultiple R-squared:  0.175,\tAdjusted R-squared:  0.1455 \nF-statistic:  5.94 on 1 and 28 DF,  p-value: 0.02141\n```\n\n\n:::\n:::\n\n\n## Broom\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Tidy summary (with optional 95% confidence interval)\nbroom::tidy(lsmodel1, conf.int = TRUE)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |  estimate| std.error| statistic|   p.value| conf.low|  conf.high|\n|:-----------|---------:|---------:|---------:|---------:|--------:|----------:|\n|(Intercept) | 20.191667| 0.7592028| 26.595880| 0.0000000| 18.63651| 21.7468231|\n|typeSelf    | -2.616667| 1.0736749| -2.437113| 0.0214145| -4.81599| -0.4173433|\n\n</div>\n:::\n:::\n\n\n:::\n\n\nKey interpretations:\n\n- Intercept: mean height of the reference level of `type` (the first level of the factor).\n\n    > This is the predicted height when the plant type is \"Cross\" fertilised, which is the reference category). The estimate is 20.1917, which means the average height for plants that are not self-fertilised is about 20.19 inches.\n\n- typeSelf (for example): estimated difference in means between Self and the reference (e.g., Cross). A negative value means Self is shorter on average.\n\n    > **typeSelf:** This coefficient tells us how the height of \"Self\" fertilized plants **differs from the reference group** (\"Cross\" fertilized plants). The estimate is -2.6167, meaning \"Self\" fertilized plants are, on average, 2.62 units shorter than \"Cross\" fertilized plants.\n\nTo confirm the reference level and means:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlevels(darwin$type)\n\ndarwin |>\n  group_by(type) |>\n  summarise(mean = mean(height))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNULL\n```\n\n\n:::\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|type  |     mean|\n|:-----|--------:|\n|Cross | 20.19167|\n|Self  | 17.57500|\n\n</div>\n:::\n:::\n\n\n\n:::{.callout-note collapse = \"true\"}\n## More information on model summaries\n\n- **The Std. Error** for each coefficient measures the uncertainty in the estimate. Smaller values indicate more precise estimates. For example, the standard error of 1.0737 for the \"typeSelf\" coefficient suggests there's some variability in how much shorter the \"Self\" fertilized plants are, but it’s reasonably precise.\n\n- **The t value** is the ratio of the estimate to its standard error ($\\frac{Mean}{Std. Error}$). The larger the t-value (either positive or negative), the more evidence there is that the estimate is different from zero.\n\n- **Pr(>|t|)** gives the p-value, which tells us the probability of observing a result as extreme as this, assuming that there is no real effect (i.e., the null hypothesis is true). In this case, a p-value of 0.0214 means there’s about a 2% chance that the difference in height between \"Self\" and \"Cross\" fertilized plants is due to random chance. Since this is below the typical cutoff of 0.05, it suggests that the difference is statistically significant.\n\n- **Significance codes**: These symbols next to the p-value indicate how strong the evidence is. In this case, one star (*) indicates a p-value below 0.05, meaning the effect is considered statistically significant.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Annotation of the summary function output](images/model summary.png){fig-align='center' width=80%}\n:::\n:::\n\n:::\n\n\n\n<div class='webex-solution'><button>The t-statistic</button>\n\n\n- The t-distribution looks like a normal distribution but with heavier tails for small samples.\n\n- As sample size grows, it approaches the normal distribution.\n\n### The t-Distribution:\n\nThe t-distribution is similar to the normal distribution but has more spread (wider tails), especially with smaller sample sizes. As the sample size increases, the t-distribution approaches the normal distribution.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09-linear-models_files/figure-html/unnamed-chunk-15-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n</div>\n\n\n:::{.callout-note collapse = \"true\"}\n## A simple write up\n\nFrom this summary model we can make conclusions about the effect of inbreeding and produce a simple write up:\n\n\"The maize plants that have been cross pollinated had an average height (mean ±S.E.) of 20.19 (± 0.76) inches and were taller on average than the self-pollinated plants, with a mean difference in height of 2.62 (±1.07) inches (t(28) = -2.44, p = 0.02)\"\n:::\n\n\n## Confidence intervals\n\n### What a 95% confidence interval means\n\n- A 95% confidence interval (CI) gives a plausible range for the true effect in the population (e.g., the true difference in mean height between Cross and Self).\n\n- If we repeated the same study many times and built a 95% CI each time, about 95% of those intervals would contain the true effect.\n\n- Narrow CIs = more precision (usually larger sample size or less variability). Wide CIs = more uncertainty.\n\n### Why you should always report CIs\n\n- A p-value is a single number about “is there evidence of an effect?” but does not tell you “how big might the effect be?”.\n\n- A CI shows both the estimated effect size and the uncertainty around it. Always report your estimate with its 95% CI.\n\nExample (difference in means):\n\n- Mean difference = 2.62 inches, 95% CI [0.42, 4.82]\n\n- Interpretation: The true difference is plausibly between 0.42 and 4.82 inches; values near 0 are less compatible with the data than values around 2–3 inches.\n\n:::{.callout-note collapse = \"true\"}\n\n### How CIs and p-values relate (two-sided tests)\n\n- For a two-sided test at α = 0.05, a 95% CI that does not include 0 corresponds to p < 0.05 (statistically significant).\n\n- If the 95% CI includes 0, then p ≥ 0.05 (not statistically significant).\n\n- This is why CIs are often described as the “interval version” of the p-value decision.\n\nTip:\n- For the question “Is there a difference?”, look at the 95% CI for the difference. If it excludes 0, there is evidence of a difference.\n\n- Be careful with overlapping CIs on separate group means: overlapping mean CIs do not necessarily imply “no difference.” The definitive check is the CI for the difference itself.\n:::\n\n\n### What changes CI width?\n\n- Sample size: larger n → narrower CI.\n\n- Variability: more spread in data → wider CI.\n\n- Confidence level: 99% CI is wider than 95% CI (stricter evidence requirement).\n\n### How to report (templates)\n\n- Difference: “The mean difference was X [95% CI: L, U].”\n\n- Group means: “Cross mean = A [95% CI: L1, U1]; Self mean = B [95% CI: L2, U2].”\n\n- Match the CI to your method (Welch, equal-variance, or robust SE) and keep the reporting consistent.\n\n### Confidence intervals (CI) in R\n\nWith a wrapper function around our model we can generate accurate 95% confidence intervals from the SE and calculated t-distribution:\n\n::: {.panel-tabset}\n\n## Base R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nconfint(lsmodel1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               2.5 %     97.5 %\n(Intercept) 18.63651 21.7468231\ntypeSelf    -4.81599 -0.4173433\n```\n\n\n:::\n:::\n\n\n## Broom\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbroom::tidy(lsmodel1, conf.int=T)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |  estimate| std.error| statistic|   p.value| conf.low|  conf.high|\n|:-----------|---------:|---------:|---------:|---------:|--------:|----------:|\n|(Intercept) | 20.191667| 0.7592028| 26.595880| 0.0000000| 18.63651| 21.7468231|\n|typeSelf    | -2.616667| 1.0736749| -2.437113| 0.0214145| -4.81599| -0.4173433|\n\n</div>\n:::\n:::\n\n\n:::\n\nBecause this follows the same layout as the table of coefficients, the output intercept row gives a 95% CI for the height of the crossed plants and the second row gives a 95% interval for the *difference in height between crossed and selfed plants*. The lower and upper bounds are the 2.5% and 97.5% of a *t*-distribution. \n\nIt is this difference in height in which we are specifically interested. \n\n\n## Robust standard errors with sandwich\n\nWhen we were first introduced to the t-test we learned about Student's (equal variance) vs Welch's test (unequal variance).\n\nIf variances differ across groups (heteroscedasticity), standard errors from `lm()` may be too optimistic (like the student's t-test). A simple fix is to use heteroskedasticity-consistent (HC) “sandwich” standard errors (like Welch's t-test).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Fit the same model\nlsmodel1 <- lm(height ~ type, data = darwin)\n\n# Robust (HC3) SEs and tests for coefficients\nlmtest::coeftest(lsmodel1, vcov. = sandwich::vcovHC(lsmodel1, type = \"HC3\"))\n\n# Robust confidence intervals for coefficients\nlmtest::coefci(lsmodel1, vcov. = sandwich::vcovHC(lsmodel1, type = \"HC3\"), level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 20.19167    0.96667 20.8879  < 2e-16 ***\ntypeSelf    -2.61667    1.11136 -2.3545  0.02579 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n                2.5 %     97.5 %\n(Intercept) 18.211535 22.1717988\ntypeSelf    -4.893183 -0.3401508\n```\n\n\n:::\n:::\n\n\nInterpretation:\n- The coefficient for `typeSelf` is still the difference in means, but its SE, t, p, and CI are now robust to unequal variances.\n\n- Use this when Levene’s test (or model check plots) suggest heteroscedasticity, or as a cautious default.\n\n:::{.callout-note collapse = \"true\"}\n\n- `sandwich::vcovHC()` computes a heteroskedasticity-consistent covariance matrix.\n\n- \"HC3\" is often preferred (like in MacKinnon & White, 1985) because it’s more reliable in small samples.\n\n- `lmtest::coeftest()` replaces the usual OLS standard errors with these robust ones.\n\n- `lmtest::coefci()` gives robust CIs with the same robust covariance matrix.\n\n:::\n\n## Assumptions: minimal, practical checks\n\nWhen we fit a linear model for a two-group comparison, we need to check whether the numbers we have generated are reliable by checking the fit of our model against some assumptions: \n\n- Normality: The t-test and lm are fairly robust for moderate sample sizes. A quick check is still useful.\n\n- Equal variances: Prefer Welch or robust SEs if this looks violated.\n\nMaking these checks is simple and quick with `performance::check_model()`\n\n\n::: {.panel-tabset}\n## Performance\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# -------------------------------------------------------------------\n# Check the NORMALITY of residuals for the linear model 'lsmodel1'\n# -------------------------------------------------------------------\n\n# Purpose:\n#  - In linear regression, residuals should ideally be normally distributed.\n#    This affects the validity of confidence intervals and p-values.\n\nnormality <- check_normality(lsmodel1)\n\n# Print the results of the normality test.\n# The output will usually include:\n#   - The type of test used (\"Shapiro-Wilk\")\n# Interpretation:\n#   - p > 0.05 → Fail to reject normality (residuals are approximately normal)\n#   - p < 0.05 → Reject normality (residuals deviate from normality)\n\nnormality\n\n# Visualize the normality check with a Q–Q plot (quantile–quantile plot).\n# \n# The plot() method for the object returned by 'check_normality()' creates:\n#   - A Q–Q plot comparing the quantiles of the residuals \n#     against the theoretical quantiles from a normal distribution.\n#   - The line represents the \"ideal\" normal distribution.\n# Argument:\n#   detrend = FALSE → Shows the standard Q–Q plot (not detrended).\n#   If TRUE, it shows the residuals from the Q–Q line (useful for subtle deviations).\n#\n# Interpretation:\n#   - Points should roughly follow the diagonal line.\n#   - Systematic deviations (S-shaped curve or tails off the line)\n#     indicate non-normal residuals.\n\nplot(normality, detrend = FALSE)\n```\n\n::: {.cell-output-display}\n![](09-linear-models_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n# -------------------------------------------------------------------\n# Check for HETEROSCEDASTICITY (unequal variances of residuals)\n# -------------------------------------------------------------------\n\n# The function 'check_heteroscedasticity()' tests whether the residuals \n# from the model have constant variance (homoscedasticity).\n# \n# Under the hood, it typically performs:\n#  - Breusch–Pagan test (default)\n# \n# Purpose:\n#  - In linear regression, we assume the variance of residuals is constant\n#    across fitted values (homoscedasticity).\n#  - Heteroscedasticity can bias standard errors and affect inference.\n\nheteroscedasticity <- check_heteroscedasticity(lsmodel1)\n\n# Print the test results.\n# Output typically includes:\n#   - The type of test used (usually \"Breusch–Pagan\")\n# Interpretation:\n#   - p > 0.05 → No evidence of heteroscedasticity (good)\n#   - p < 0.05 → Residual variance changes with fitted values (problematic)\n\nheteroscedasticity\n\n# Visualize the results with a residuals-vs-fitted plot.\n# The plot() method for 'check_heteroscedasticity()' creates:\n#   - A scatterplot of fitted values (x-axis) vs. residuals (y-axis)\n#   - A smoothing line (usually loess) that helps detect trends.\n# \n# Interpretation:\n#   - Random scatter around zero → Homoscedasticity (good)\n#   - Funnel shape or systematic pattern → Heteroscedasticity (bad)\n# Unfortunately this plot is a BIT RUBBISH when comparing groups - check out the basic R function instead\nplot(heteroscedasticity)\n```\n\n::: {.cell-output-display}\n![](09-linear-models_files/figure-html/unnamed-chunk-19-2.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: Non-normality of residuals detected (p < .001).\nWarning: Heteroscedasticity (non-constant error variance) detected (p = 0.047).\n```\n\n\n:::\n:::\n\n\n## Base R\n\nWe don't *have* to use performance, base R can visualise these with the `plot()` function\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ---------------------------------------------------------------\n# Plot 1: Normal Q–Q Plot\n# ---------------------------------------------------------------\nplot(lsmodel1, which = 2)\n```\n\n::: {.cell-output-display}\n![](09-linear-models_files/figure-html/unnamed-chunk-20-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n# ---------------------------------------------------------------\n# Plot 2: Residuals vs Fitted values\n# ---------------------------------------------------------------\nplot(lsmodel1, which = 1)\n```\n\n::: {.cell-output-display}\n![](09-linear-models_files/figure-html/unnamed-chunk-20-2.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n## Simple write-up\n\nFrom the Welch t-test (or the linear model), you can write:\n\n“The maize plants that have been cross-pollinated were taller on average than the self-pollinated plants. The mean difference in height was approximately 2.62 inches (95% CI: 0.34 to 4.89), t(df ≈ 28) ≈ 2.35, p ≈ 0.026.”\n\nTip: Match the df and exact numbers to the specific method you report (Welch vs equal-variance vs robust) as they **will be slightly different**. Using `rstatix::t_test(..., detailed = TRUE)` or `broom::tidy(..., conf.int = TRUE)` ensures you have all values at hand.\n\n\n\n:::{.callout-note, collapse = \"true\"}\n## Estimating means\n\nOne limitation of the table of coefficients output is that it doesn't provide the mean and standard error of the *other* treatment level (only the difference between them). If we wish to calculate the \"other\" mean and SE then we can get R to do this.\n\n### Changing the intercept\n\nOne way to do this is to change the levels of the type variable as a factor:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Perform linear regression on darwin data with Self as the intercept\ndarwin |> \n  # Convert 'type' column to a factor\n  mutate(type = factor(type)) |>\n  # Relevel 'type' column to specify the order of factor levels\n  mutate(type = fct_relevel(type, c(\"Self\", \"Cross\"))) |>\n  # Fit linear regression model with 'height' as the response variable and 'type' as the predictor\n  lm(height ~ type, data = _) |>\n  # Tidy the model summary\n  broom::tidy()\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |  estimate| std.error| statistic|   p.value|\n|:-----------|---------:|---------:|---------:|---------:|\n|(Intercept) | 17.575000| 0.7592028| 23.149282| 0.0000000|\n|typeCross   |  2.616667| 1.0736749|  2.437113| 0.0214145|\n\n</div>\n:::\n:::\n\n\nAfter releveling, the self treatment is now taken as the intercept, and we get the estimate for it's mean and standard error\n\n### Emmeans\n\nWe could also use the package [`emmeans`](https://aosmith.rbind.io/2019/03/25/getting-started-with-emmeans/) and its function `emmeans()` to do a similar thing\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calculate estimated marginal means (EMMs) using emmeans package\nmeans <- emmeans::emmeans(lsmodel1, specs = ~ type)\n\nmeans\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n type  emmean    SE df lower.CL upper.CL\n Cross   20.2 0.759 28     18.6     21.7\n Self    17.6 0.759 28     16.0     19.1\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\nThe advantage of emmeans is that it provides the mean, standard error and 95% confidence interval estimates of all levels from the model at once (e.g. it relevels the model multiple times behind the scenes). \n\n\n`emmeans` also gives us a handy summary to include in data visuals that combine raw data and statistical inferences. These are standard `ggplot()` outputs so can be [customised as much as you want](#intro-to-grammar).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Convert the 'means' object to a tibble\nmeans |>\n  as_tibble() |>\n  # Create a plot using ggplot\n  ggplot(aes(x = type, y = emmean)) +\n  # Add point estimates with error bars\n  geom_pointrange(aes(ymin = lower.CL, ymax = upper.CL))\n```\n\n::: {.cell-output-display}\n![](09-linear-models_files/figure-html/unnamed-chunk-23-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nNotice that no matter how we calculate the estimated SE (and therefore the 95% CI) of both treatments is the same. This is because as mentioned earlier the variance is a pooled estimate, e.g. variance is not being calculate separately for each group. The only difference you should see in SE across treatments will be if there is a difference in *sample size* between groups. \n\n:::\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}