{
  "hash": "68106ffd1e724b98dbab5b960493891b",
  "result": {
    "engine": "knitr",
    "markdown": "# Data insights {#sec-insights}\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nFor this exercise, we propose that our task is to generate insights into the relationship between **bill (culmen) length** and **bill (culmen) depth** in penguins. Our goal is to answer the question: *Is there a meaningful relationship between these two measurements?* Understanding this relationship can provide valuable insights into the physical characteristics of different penguin species and how they may vary.\n\n:::{.callout-important}\nYou should be working in the script you made in the last session check it contains everything contained in {@sec-save-script} and runs cleanly (no errors).\n\nTest this by making sure you have set your project up correctly (see {@blank}), restart your R session, and run your current script. \n\n:::\n\n:::{.callout-note collapse = \"true\"}\n### Quick Recap\n\nPreviously you:\n1. Imported data (`readRDS()`, `read_csv()`), saved intermediate objects.\n2. Cleaned names (`janitor::clean_names()`), checked types (`glimpse()` / `skimr::skim()`).\n3. Identified missing values, duplicates, inconsistent factor levels.\n4. Used grouping (dplyr) to summarise.\n5. Saved a reusable script.\n\nToday we build forward — we assume basic cleaning is done.\n\n:::\n\n\n::: {.callout-important}\n### Today’s Workflow\n\n**summarise → visualise → think causally**\n\n1. Summarise: Get core descriptive statistics (center, spread, counts).\n2. Visualise: Use multiple plot types to expose structure and anomalies.\n3. Think causally: Ask whether patterns could be explained by grouping variables (e.g. species), and avoid misleading pooled summaries.\n:::\n\n## Understanding the Variables\n\nOur key variables are:\n\n- **Culmen Length (bill length)**: This measures the length of the penguin's bill, an important feature related to feeding.\n\n- **Culmen Depth (bill depth)**: This measures the thickness of the penguin's bill.\n\nWe will also routinely consider: Species, Sex, Island, Year, Flipper length(mm) and Body Mass (g).\n\n## What should we consider in our analysis?\n\n### Data Types\n\n- Bill length and depth: **continuous numerical**.  \n\n- Species, sex, island, year: **categorical** (year is numeric but often used as a factor in exploratory stratification).\n\n:::{.callout-note collapse = \"true\"}\n### Why this matters: \n\nKnowing whether a variable is numerical or categorical will influence how we visualize it and which statistical methods we use. For instance, numerical data might be plotted using histograms, while categorical data could be displayed using bar charts or boxplots.\n\n:::\n\n### Central Tendency & Variation\n\nNext, we’ll want to understand the central tendency of our data. Central tendency refers to the average or most common values in a dataset:\n\n- Mean: The average value (sum of all values divided by the number of values).\n\n- Median: The middle value when data is sorted from lowest to highest, which is especially useful if the data is skewed or contains outliers.\n\n- Mode: The most frequently occurring value in the dataset (not always relevant for continuous data).\n\n:::{.callout-note collapse = \"true\"}\n### Why this matters: \nUnderstanding the average bill length and depth helps us get a sense of what is \"normal\" for our penguins. Additionally, comparing these statistics across different species or islands could reveal differences in penguin populations.\n\n:::\n\n### Relationships\n\nNow, we dive into the heart of our analysis: exploring the relationship between culmen length and culmen depth. To investigate this, we can use visual tools like <a class='glossary'>scatterplots<span class='def'>A graph that displays the relationship between two numerical variables by plotting data points on an X and Y axis.</span></a> , which allow us to plot one variable against the other and visually check for patterns or trends.\n\nWe might also want to calculate a <a class='glossary'>correlation coefficient<span class='def'>A numerical value ranging from -1 to 1 that measures the strength and direction of the linear relationship between two variables.</span></a> to quantify the strength of the relationship between bill length and bill depth. \nIf we find a strong correlation, we can say that these two measurements tend to move together — for example, as the bill length increases, so might the bill depth.\n\n:::{.callout-note collapse = \"true\"}\n### Why this matters: \n\nIdentifying the relationship between variables is critical to making meaningful conclusions. If bill length and depth are highly correlated, we can begin to explore why this might be the case — perhaps certain penguin species have distinct bill shapes that differ from others.\n:::\n\n### Confounding Variables\n\nA <a class='glossary'>confounding variable<span class='def'>A variable that affects both the independent and dependent variables, potentially distorting the observed relationship between them.</span></a> influences both variables in a relationship (e.g. species affects both length and depth). Ignoring it can distort or reverse observed trends \n\n\n:::{.callout-note collapse = \"true\"}\n### Why this matters:  \n\nIgnoring confounding variables could lead us to incorrect conclusions. For instance, if we see a strong relationship between bill length and depth, it could simply be due to species differences, rather than a true relationship across all penguins.\n:::\n\n### Asking New Questions\n\nEvery step of the analysis leads to new questions. This is a natural part of the data exploration process (e.g. “Is this consistent across species?”)\n\n\n### Data Checking (Recap)\n\nAlready completed in {@sec-dplyr} a reminder why it matters:\n\n- Confirm variable formats.\n\n- Locate & classify missingness.\n\n- Count observations per key groups to assess balance.\n\n- Ensure cleaned, informative names (see {@sec-names})\n\n\n## Activity: Quick Descriptive Summaries\n\nWe’ll start with descriptive statistics—numerical summaries that describe the main features of a dataset.\n\nFor a single variable (here: \"culmen length in mm\"), the most common statistics are:\n\n| Statistic   | What it tells us                                    |\n| ----------- | --------------------------------------------------- |\n| **n**       | Sample size (how many penguins are included)        |\n| **Mean**    | The average value                                   |\n| **Median**  | The “middle” value (half above, half below)         |\n| **SD**      | Standard deviation = typical distance from the mean |\n| **IQR**     | Interquartile range = spread of the middle 50%      |\n| **Min/Max** | Smallest and largest values (range)                 |\n\n\nThink of **mean/median** as *center*, and **SD/IQR/min/max** as *spread*.\n\nCheck out [StatQuest](https://statquest.org/statistics-fundamentals-the-mean-variance-and-standard-deviation/) for some great explainer/recap videos.\n\n### Overall distribution\n\nWhat does the culmen length look like across *all* penguins?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |>                         \n  summarise(                        # calculate summary statistics\n    n = n(),                        # count of observations (sample size)\n    mean = mean(culmen_length_mm,   # average culmen length, ignoring missing values\n                na.rm = TRUE),\n    median = median(culmen_length_mm, \n                   na.rm = TRUE),   # middle value of culmen length\n    sd = sd(culmen_length_mm, \n            na.rm = TRUE),          # standard deviation (spread around the mean)\n    iqr = IQR(culmen_length_mm, \n              na.rm = TRUE),        # interquartile range (spread of middle 50%)\n    .groups = \"drop\"                \n  )\n```\n:::\n\n\n\n\n\n### By species\n\nDo species differ in average culmen length or variability?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |>\n  group_by(species) |>         # split the data into subgroups by species\n  summarise(                  # within each subgroup, calculate summary statistics\n    n = n(),\n    mean = mean(culmen_length_mm, na.rm = TRUE),\n    median = median(culmen_length_mm, na.rm = TRUE),\n    sd = sd(culmen_length_mm, na.rm = TRUE),\n    iqr = IQR(culmen_length_mm, na.rm = TRUE),\n    .groups = \"drop\"           # remove grouping in the final output\n  )\n```\n:::\n\n\n:::{.callout-note}\n\n## Stop & Reflect\n\n- How do the species means compare to the overall mean?\n\n- Why might it be misleading to report only the *overall mean* without looking at subgroups?\n\n- Why is species a useful/informative choice to split data by?\n\n- Could other variables also affect culmen length?\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n- **Species vs. overall mean** → The species means are quite different from each other; the overall mean blends them together and hides those differences.\n\n- **Why overall mean can mislead** → If we only reported the overall mean, we’d miss meaningful biological variation according to important subgroups.\n\n- **Why species is useful** → Biology suggests species differ systematically in body size and morphology, so species plausibly causes variation in culmen length.\n\n- **Other variables** → Yes \n                      - sex (sexual dimorphism): males and females can often have different average body size \n                      - island: possible *if* they experience very different environmental conditions\n                      - year: possible *if* they experience different environmental conditions\n                      - body mass: possible - but body mass could also be indirectly affected by species *or* environment\n\n\n</div>\n\n\n:::\n\n### By species *and* sex\n\nDo males and females within a species look different? Which subgroups are most variable?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |>                         \n  group_by(species, sex) |>         # split the data into subgroups by species AND sex\n  summarise(                        # within each subgroup, calculate summary statistics\n    n = n(),                        \n    mean = mean(culmen_length_mm,   \n                na.rm = TRUE),\n    median = median(culmen_length_mm, \n                   na.rm = TRUE),   \n    sd = sd(culmen_length_mm, \n            na.rm = TRUE),         \n    iqr = IQR(culmen_length_mm, \n              na.rm = TRUE),       \n    .groups = \"drop\"                # remove grouping in the final output\n  )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|species   |sex    |  n|     mean| median|       sd|   iqr|\n|:---------|:------|--:|--------:|------:|--------:|-----:|\n|Adelie    |Female | 73| 37.25753|  37.00| 2.028883| 2.900|\n|Adelie    |Male   | 73| 40.39041|  40.60| 2.277131| 2.500|\n|Adelie    |NA     |  6| 37.84000|  37.80| 2.802320| 0.300|\n|Chinstrap |Female | 34| 46.57353|  46.30| 3.108669| 1.950|\n|Chinstrap |Male   | 34| 51.09412|  50.95| 1.564558| 1.925|\n|Gentoo    |Female | 58| 45.56379|  45.50| 2.051247| 3.025|\n|Gentoo    |Male   | 61| 49.47377|  49.50| 2.720594| 2.400|\n|Gentoo    |NA     |  5| 45.62500|  45.35| 1.374470| 1.975|\n\n</div>\n:::\n:::\n\n\n::: {.callout-note}\n\n## Stop & Reflect\n\n- Which species + sex subgroup has the highest variation (SD/IQR)?\n\n- Do any subgroups have very small n? Why might that matter if we want to draw reliable conclusions?\n\n- Small or imbalanced groups can make it difficult to know whether differences are real or due to chance.\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\nWhen a subgroup has **very few observations** (small n), any summary statistics we calculate—mean, median, standard deviation, or IQR—are **less reliable**. Small groups are more sensitive to random variation: a single unusually large or small value can dramatically change the mean or SD.\n\nSimilarly, when subgroups are **imbalanced** (some very large, some very small), comparing averages across groups can be misleading, because the small groups contribute little information and their estimates are highly uncertain.\n\n\n</div>\n\n:::\n\n\n::: {.callout-tip collapse = \"true\"}\n\n## summary() vs summarise()\n\n### Base R: quick glance (not grouped)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(penguins$culmen_length_mm)\n```\n:::\n\n\n### Tidyverse: grouped\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |> group_by(species) |>\n  summarise(mean = mean(culmen_length_mm, na.rm=TRUE),\n            sd = sd(culmen_length_mm, na.rm=TRUE))\n```\n:::\n\n\n👉 Use `summary()` for a fast check, but `summarise()` when you need flexible or grouped results.\n:::\n\n\n## Explore the distribution of categories\n\nUnderstanding how your data is distributed across important grouping variables is essential for context. In this case, the Palmer Penguins dataset includes key groupings such as **species, island, and year**, which might have significant effects on the relationships we want to study (e.g., between bill length and bill depth). By summarising and visualising the distribution of these variables, we can ensure that our analyses account for group-level differences, leading to more robust insights.\n\n### Frequency\n\nBy grouping the data according to the species variable, we can calculate the total count (`n`) of penguins within each species. This summary provides a clear understanding of how the penguins are distributed across the different species in the dataset. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |> \n  # calculations applied per species\n  group_by(species) |> \n  # summarise the number of observations in each group\n  summarise(n = n())\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|species   |   n|\n|:---------|---:|\n|Adelie    | 152|\n|Chinstrap |  68|\n|Gentoo    | 124|\n\n</div>\n:::\n:::\n\n\n**Question** Are there 152 different penguins in our dataset? <select class='webex-select'><option value='blank'></option><option value=''>TRUE</option><option value='answer'>FALSE</option></select>\n\n\n<div class='webex-solution'><button>Explanation</button>\n\n\nThe functions above count the number of rows of data - we need to determine if these are repeated or independent measures. We should remember that there is a column called `individual_id` if we use the `n_distinct()` function we can count how many unique IDs we have\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |> \n  # calculations applied per species\n  group_by(species) |> \n  # summarise the number of observations in each group\n  summarise(n_unique = n_distinct(individual_id))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|species   | n_unique|\n|:---------|--------:|\n|Adelie    |      132|\n|Chinstrap |       58|\n|Gentoo    |       94|\n\n</div>\n:::\n:::\n\n\nNow we can see that there are only 132 *different* Adelie penguins in our data\n\n\n</div>\n\n\n\n### Relative Frequency\n\nIn addition to counting the total number of penguins in each species, calculating the relative frequency can be a useful summary. Relative frequency shows the proportion or percentage of observations in each category relative to the total number of observations. This helps us understand not only the absolute count but also how common each species is compared to the others.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_obs_species <- penguins |> \n  group_by(species) |> \n  summarise(n = n()) |> \n  # use mutate to make a new column relative frequency\n  mutate(prob_obs = n/sum(n))\n\nprob_obs_species\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|species   |   n|  prob_obs|\n|:---------|---:|---------:|\n|Adelie    | 152| 0.4418605|\n|Chinstrap |  68| 0.1976744|\n|Gentoo    | 124| 0.3604651|\n\n</div>\n:::\n:::\n\n\nSo about 44% of our sample is made up of observations from Adelie penguins. When it comes to making summaries about categorical data, that's about the best we can do, we can make observations about the most common categorical observations, and the relative proportions.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |> \n  mutate(species = fct_relevel(species,       # re-order the species factor levels\n                               \"Adelie\",      # first level\n                               \"Gentoo\",      # second level\n                               \"Chinstrap\")) |> # third level\n  # now species is a factor with a defined order\n  ggplot() +                                  # start a ggplot\n  geom_bar(aes(x = species),                  # create a bar chart counting observations per species\n           fill = \"steelblue\",               # fill bars with blue color\n           width = 0.8) +                     # width of bars\n  labs(x = \"Species\",                         # label x-axis\n       y = \"Number of observations\") +       # label y-axis\n  geom_text(data = prob_obs_species,          # add text labels on top of bars\n            aes(y = (n + 10),                # position labels slightly above each bar\n                x = species,\n                label = scales::percent(prob_obs))) + # show proportion as a percentage\n  coord_flip()                                # flip coordinates: horizontal bars instead of vertical\n```\n\n::: {.cell-output-display}\n![](07-data-insights_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' fig-alt='Horizontal bar chart showing counts per species with percentage labels.' width=100%}\n:::\n:::\n\n\n\n:::{.callout-tip collapse = \"true\"}\n## Big-picture\n\n- `forcats::fct_relevel()`: ensures bars appear in a meaningful order (Adelie → Gentoo → Chinstrap).\n\n- `ggplot::geom_bar()`: counts penguins per species and plots as bars.\n\n- `ggplot::geom_text()`: overlays percentage labels above each bar for clarity.\n\n- `ggplot::coord_flip()`: makes the bar chart horizontal, which is often easier to read when labels are long.\n\n:::\n\n## Two or more categories\n\nWhen investigating the distribution of observations, it’s important to consider how other variables might influence this relationship, such as sex, species or observations across years.\n\n\nUnderstanding how frequency is broken down by island, species year and sex might be useful.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |> \n  group_by(island, year, species, sex) |> \n  summarise(n = n()) \n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|island    | year|species   |sex    |  n|\n|:---------|----:|:---------|:------|--:|\n|Biscoe    | 2007|Adelie    |Female |  5|\n|Biscoe    | 2007|Adelie    |Male   |  5|\n|Biscoe    | 2007|Gentoo    |Female | 16|\n|Biscoe    | 2007|Gentoo    |Male   | 17|\n|Biscoe    | 2007|Gentoo    |NA     |  1|\n|Biscoe    | 2008|Adelie    |Female |  9|\n|Biscoe    | 2008|Adelie    |Male   |  9|\n|Biscoe    | 2008|Gentoo    |Female | 22|\n|Biscoe    | 2008|Gentoo    |Male   | 23|\n|Biscoe    | 2008|Gentoo    |NA     |  1|\n|Biscoe    | 2009|Adelie    |Female |  8|\n|Biscoe    | 2009|Adelie    |Male   |  8|\n|Biscoe    | 2009|Gentoo    |Female | 20|\n|Biscoe    | 2009|Gentoo    |Male   | 21|\n|Biscoe    | 2009|Gentoo    |NA     |  3|\n|Dream     | 2007|Adelie    |Female |  9|\n|Dream     | 2007|Adelie    |Male   | 10|\n|Dream     | 2007|Adelie    |NA     |  1|\n|Dream     | 2007|Chinstrap |Female | 13|\n|Dream     | 2007|Chinstrap |Male   | 13|\n|Dream     | 2008|Adelie    |Female |  8|\n|Dream     | 2008|Adelie    |Male   |  8|\n|Dream     | 2008|Chinstrap |Female |  9|\n|Dream     | 2008|Chinstrap |Male   |  9|\n|Dream     | 2009|Adelie    |Female | 10|\n|Dream     | 2009|Adelie    |Male   | 10|\n|Dream     | 2009|Chinstrap |Female | 12|\n|Dream     | 2009|Chinstrap |Male   | 12|\n|Torgersen | 2007|Adelie    |Female |  8|\n|Torgersen | 2007|Adelie    |Male   |  7|\n|Torgersen | 2007|Adelie    |NA     |  5|\n|Torgersen | 2008|Adelie    |Female |  8|\n|Torgersen | 2008|Adelie    |Male   |  8|\n|Torgersen | 2009|Adelie    |Female |  8|\n|Torgersen | 2009|Adelie    |Male   |  8|\n\n</div>\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |> \n  ggplot(aes(x = species,                  # x-axis = species\n             fill = sex)) +               # color bars by sex\n  geom_bar(width = 0.8,                     # width of the bars\n           position = position_dodge()) +  # dodge bars so males/females are side by side\n  labs(x = \"Species\",                       # x-axis label\n       y = \"Number of observations\") +     # y-axis label\n  facet_grid(island ~ year)                 # create a grid of plots: rows = island, columns = year\n```\n\n::: {.cell-output-display}\n![](07-data-insights_files/figure-html/unnamed-chunk-12-1.png){fig-align='center' fig-alt='Grid barplot of counts by year and location' width=100%}\n:::\n:::\n\n\n:::{.callout-tip collapse = \"true\"}\n## Big-picture\n\n- `fill = sex` → bars are colored by sex, so we can compare males vs females within each species.\n\n- `position_dodge()` → avoids stacking bars; puts male and female bars side by side for direct comparison.\n\n- `facet_grid(island ~ year)` → splits the plot into a grid showing counts for each island (rows) and year (columns).\n\n- This is a multi-dimensional descriptive view: you can see how species, sex, island, and year all relate to counts.\n\n:::\n\nBy thinking about how categories might interact, we can identify interesting patterns or potential issues that could impact our analysis or data interpretation. Careful consideration of these interactions helps us ensure the validity of our findings. For instance:\n\n:::{.callout-important collapse = \"true\"}\n\n## Thinking about distributions\n\n- Sex Distribution: Looking at the patterns of male and female penguins, I’m reassured that the number of males and females observed is roughly equal across species and locations. This balance is important because unequal representation of sexes could bias our results, particularly in biological traits like bill length or body mass. Since there’s no imbalance, we can confidently proceed without worrying about gender skewing our insights.\n\n- Species Distribution by Island: There are different numbers of species on different islands, but this variation remains consistent across years. This suggests that the observed species distributions likely reflect true ecological patterns, rather than inconsistencies in data collection. If this trend were erratic across years, we might suspect sampling issues, but the consistency provides confidence in the accuracy of species representation.\n\n- Consistency Across Years: The number of penguins observed is consistent across years, meaning we don’t see major fluctuations in sample size. This consistency is important because significant changes could suggest variations in data collection methods or environmental factors affecting penguin populations. A steady count ensures that any trends or patterns we observe are less likely to be the result of sampling inconsistencies.\n\n- Missing Data for Sex: While there are some missing values for the sex variable, these gaps are small and don’t fit any obvious pattern. This suggests that the missing data is likely random and not linked to a particular species, location, or time period. Since the missing values are few and do not show a clear bias, we can choose to ignore these gaps in the analysis with reasonable confidence that they won’t heavily skew our results.\n\nBy reflecting on these patterns, we can be more confident in the integrity of the data and proceed with analysis, knowing that key variables are well-represented and that any missing data or inconsistencies are minimal and manageable.\n\n:::\n\n## Missing data\n\nIn the previous section, we identified some missing data, particularly for the sex variable, and noted that it was relatively small and likely random, meaning we could safely remove it from calculations without concern for <a class='glossary'>bias<span class='def'>A systematic error or distortion in data collection or analysis that leads to inaccurate conclusions or results.</span></a> . However, when it comes to our variables of interest, such as `culmen length` and `culmen depth`, it's worth taking a closer look at the missing values to understand if they occur in any particular patterns or groupings.\n\nWe previously used functions like `skimr::skim()` and `summary()` to find that there are two missing values each for culmen length and depth. Although this small amount of missing data is unlikely to introduce significant bias, it’s still a good practice to investigate where these missing values are located in the dataset. Identifying patterns or specific groups (e.g., certain species or islands) associated with the missing values can help ensure that the missing data is not clustered in a way that could subtly affect our analysis.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |>\n  # Filter rows where culmen length is NA\n  filter(is.na(culmen_length_mm)) |> \n  # Group by species, sex and island\n  group_by(species, sex, year, island) |>                 \n  summarise(n_missing = n())    \n\npenguins |>\n  filter(is.na(culmen_depth_mm)) |>         \n  group_by(species, sex, year, island) |>               \n  summarise(n_missing = n())    \n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|species |sex | year|island    | n_missing|\n|:-------|:---|----:|:---------|---------:|\n|Adelie  |NA  | 2007|Torgersen |         1|\n|Gentoo  |NA  | 2009|Biscoe    |         1|\n\n</div><div class=\"kable-table\">\n\n|species |sex | year|island    | n_missing|\n|:-------|:---|----:|:---------|---------:|\n|Adelie  |NA  | 2007|Torgersen |         1|\n|Gentoo  |NA  | 2009|Biscoe    |         1|\n\n</div>\n:::\n:::\n\n\nThere is data missing from one Adelie penguin in 2007 on Torgersen, and one value missing from a Gentoo penguin in 2009 on Biscoe. This is true for both culmen length and depth, it is probably the same penguin in both cases, but how could we change our code to be sure?\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |>\n  filter(is.na(culmen_length_mm)) |> \n# ADD individual id into group_by arguments\n  group_by(species, sex, year, island, individual_id) |>                 \n  summarise(n_missing = n())    \n\npenguins |>\n  filter(is.na(culmen_depth_mm)) |>         \n  group_by(species, sex, year, island, individual_id) |>               \n  summarise(n_missing = n())    \n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|species |sex | year|island    |individual_id | n_missing|\n|:-------|:---|----:|:---------|:-------------|---------:|\n|Adelie  |NA  | 2007|Torgersen |N2A2          |         1|\n|Gentoo  |NA  | 2009|Biscoe    |N38A2         |         1|\n\n</div><div class=\"kable-table\">\n\n|species |sex | year|island    |individual_id | n_missing|\n|:-------|:---|----:|:---------|:-------------|---------:|\n|Adelie  |NA  | 2007|Torgersen |N2A2          |         1|\n|Gentoo  |NA  | 2009|Biscoe    |N38A2         |         1|\n\n</div>\n:::\n:::\n\n\n</div>\n\n\n\n### Handling missing values\n\nThree main strategies: \n\n1. Drop all rows with *any* NA (`drop_na()`): simple but can remove lots - **the nuclear option**\n\n2. Drop NAs in specific columns only.\n\n3. Keep rows, use `na.rm = TRUE` inside summary functions (least destructive).\n\n#### `drop_na()` on everything before we start. \n\nUsing drop_na() to remove rows that contain any missing values across all variables can be useful, but it also runs the risk of losing a large portion of the data.\n\n- Pros: It's a simple, all-in-one solution for datasets where missing values are widespread and problematic.\n\n- Cons: This method may remove entire rows of data, even if the missing value is only in a single, unimportant column. This can lead to significant data loss if many rows have missing values in non-critical variables.\n\n\n#### `drop_na()` on a particular variable. \n\nAnother approach is to remove rows with missing data in a specific variable, such as `body_mass_g`. This is less drastic but still needs to be done thoughtfully, especially if you overwrite the original dataset with the modified version. It's often better to drop `NA`s temporarily for specific analyses or calculations.\n\n- Pros: You retain more data because you only remove rows with missing values in the column that matters for your current analysis.\n\n- Cons: You might still lose useful information from other columns. If you overwrite the dataset permanently (e.g., using `penguins <- penguins |> drop_na(body_mass_g))`, you can’t recover the dropped rows without reloading the data.\n\n#### Use arguments inside functions \n\nA more cautious approach is to handle missing data within summary or calculation functions, using the `na.rm = TRUE` argument. Many summary functions (like `mean()`, `median()`, or `sum()`) include this argument, which, when set to `TRUE`, excludes `NA` values from the calculation. This allows you to keep missing values in the dataset but ignore them only when performing calculations.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |> \n  summarise(\n    mean_body_mass = mean(body_mass_g, na.rm = T)\n  )\n```\n:::\n\n\n- Pros: This is the least destructive option because it allows you to handle missing data without removing any rows from the dataset. You only exclude `NA` values during specific calculations.\n\n- Cons: This doesn’t remove missing data, so you need to ensure that they won’t cause issues later in other analyses (e.g., regressions or visualizations).\n\n## Continuous distributions\n\n::: {.callout-important}\nIn the examples below, adapt code to examine BOTH culmen length and culmen depth.\n:::\n\nA continuous variable is a type of numerical variable that can take an infinite number of values within a given range. Unlike categorical variables, which represent distinct groups or categories, continuous variables can represent quantities that can be measured with fine precision. Examples include height, weight, temperature, or in the case of the Palmer Penguins dataset, culmen length and culmen depth.\n\n\n### Histograms\n\nThis is the script to plot a frequency distribution, we only specify an x variable, because we intend to plot a <a class='glossary'>histogram<span class='def'>A graphical representation of the distribution of a dataset by grouping data into bins and showing the frequency of observations within each bin.</span></a> , and the y variable is always the count of observations. Here we ask the data to be presented in 10 equally sized bins of data. In this case chopping the x axis range into 10 equal parts and counting the number of observations that fall within each one.\n\nHistograms are helpful because they show the distribution of a single numerical variable. They divide the data into \"bins\" (ranges of values) and count how many data points fall into each bin. This helps you:\n\nSee the shape of the data: You can easily spot if the data is normally distributed, skewed, or has multiple peaks (modes).\nIdentify data spread: Histograms help you understand the spread or range of your data values.\nDetect outliers: Unusually high or low values become more noticeable in a histogram.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |> \n  ggplot()+\n  geom_histogram(aes(x=culmen_length_mm),\n                 bins=10)\n```\n\n::: {.cell-output-display}\n![](07-data-insights_files/figure-html/Histogram of culmen length with 10 bins.-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n:::{.callout-tip collapse = \"true\"}\n\n## Change the bin argument\n\nTry different `bins` values (e.g. 8, 15, 25) and observe changes.\n\nIt's usually a very good idea to see how the use of different numbers of data \"bins\" changes our understanding of the distribution\n\n:::\n\n### Boxplots\n\nA <a class='glossary'>boxplot<span class='def'>A compact visual summary of a datasets distribution, showing the median, interquartile range (IQR), and outliers.</span></a> is a powerful tool for visualizing the distribution of a numerical variable in a compact and easy-to-read format. They provide a wealth of information about the data, including its central tendency, spread, and presence of outliers, while also allowing for comparisons across different groups. Here’s why boxplots are particularly useful:\n\n- Central Tendency: The middle line within the box represents the median value of the data. Unlike the mean, which can be influenced by extreme values, the median provides a robust measure of central tendency, especially for skewed data.\n\n- Spread and Variability: The box itself shows the interquartile range (IQR), which represents the spread of the middle 50% of the data. A wider box means more variability in the data, while a narrower box indicates that the data is more tightly clustered around the median.\n\n- Outliers: Boxplots are particularly useful for identifying <a class='glossary'>outliers<span class='def'>Data points that are significantly different from the rest of the dataset, often lying far from the median or mean.</span></a>  — data points that fall far outside the typical range of values. These are shown as individual points beyond the \"whiskers\" (the lines extending from the box), making it easy to spot extreme values that could affect your analysis.\n\n- Comparison Between Groups: One of the greatest strengths of boxplots is their ability to compare distributions across different groups. By plotting multiple boxplots side by side (e.g., for different penguin species), you can easily see how a variable's distribution changes between categories, helping to highlight differences or similarities between groups.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |> \n  ggplot()+\n  geom_boxplot(aes(x=culmen_length_mm))+\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](07-data-insights_files/figure-html/Horizontal boxplot of culmen length.-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n## Continuous and categorical\n\nWhen you have a continuous variable (like culmen length) and want to explore how its distribution varies across a categorical variable (like species), visualizing the data is the best place to start. Simple figures allow us to easily see potential patterns and relationships between the variables.\n\nTo investigate how culmen length varies between different penguin species, we can create a simple boxplot that shows the distribution of culmen lengths for each species. This will help us quickly understand whether the different species tend to have different culmen lengths and whether any species has more variability or outliers than others.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |> \n    ggplot(aes(x = species,\n               y = body_mass_g,\n               fill = species))+\n    geom_boxplot(width = 0.2)+\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](07-data-insights_files/figure-html/unnamed-chunk-16-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nBy subgrouping the data, such as looking at the distribution of culmen length by species, we can more easily identify outliers within each group. When we analyze all penguins together, outliers might be harder to spot or might seem more extreme. However, when we break the data down by species, we can see that what might have appeared as an outlier in the overall data may actually be a typical value within a specific group.\n\nThis shows us that outliers are context-specific. A value that is unusually large or small for one species might fall well within the normal range for another species. Subgrouping helps us understand that outliers are not absolute—they depend on the context of the data and the groups being compared. This insight is crucial for accurate analysis, as it helps us avoid labeling a data point as unusual without considering its appropriate context.\n\n### Density plots\n\nHistograms and <a class='glossary'>density plots<span class='def'>A density plot is a visualization of the distribution of a continuous numerical variable, acting as a smoothed, continuous version of a histogram. It uses a mathematical technique called kernel density estimation to draw a smooth curve that estimates the probability distribution of the data, making it easier to see the underlying shape and overall pattern compared to a histogram</span></a> are both useful tools for visualizing the distribution of a continuous variable, but they present the information in slightly different ways.\n\n- Histograms divide the data into bins and count how many data points fall into each bin. This gives a blocky visual representation of the data's distribution and is great for showing the frequency of data points within specific ranges. The choice of bin width can influence how smooth or rough the histogram looks, and it provides an easy way to understand how the data is spread out.\n\n- Density plots, on the other hand, provide a smoothed estimate of the data distribution. Instead of counting data points in bins, a density plot estimates the probability density of the variable, giving a continuous curve that helps visualize the shape of the data. The area under the curve of a density plot sums to 1, making it particularly useful when comparing distributions between groups, as it normalizes the data regardless of sample size.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins|> \n  ggplot(aes(fill = species))+\n  geom_density(aes(x = culmen_length_mm),\n                   position = \"identity\",\n                   alpha = 0.6)\n```\n\n::: {.cell-output-display}\n![](07-data-insights_files/figure-html/unnamed-chunk-17-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n### Ridgeline density plots\n\nThe package `ggridges` @R-ggridges provides some excellent extra geoms to supplement ggplot `ggridges::geom_density_ridges()`. One of its most useful features is to to allow different groups to be mapped to the y axis, so that histograms are more easily viewed.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggridges)\n\nggplot(penguins, aes(x = culmen_length_mm, \n                     y = species)) + \n  ggridges::geom_density_ridges()\n```\n\n::: {.cell-output-display}\n![](07-data-insights_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nWhen a density plot shows double peaks (also known as bimodal distribution), it often suggests that the data may contain two distinct groups or underlying patterns that are not immediately visible. In such cases, subgrouping the data can help clarify these peaks. By breaking the data down into categories—such as species, gender, or location—we can explore whether the peaks correspond to meaningful subgroups within the dataset.\n\nFor example, in the Palmer Penguins dataset, a bimodal distribution of bill length might indicate that different species have distinct bill lengths, each contributing to one of the peaks. Subgrouping by species would allow us to visualize separate distributions for each species and better understand the source of the variation.\n\nSubgrouping helps us gain clarity by revealing if the apparent double peaks are caused by the presence of multiple groups, and it allows us to analyze these groups separately, leading to more accurate insights. \n\nLet's see what happens when we account for sex: \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |> \n  drop_na() |> \nggplot(aes(x = culmen_length_mm, \n                     y = species, fill = sex)) + \n    ggridges::geom_density_ridges()\n```\n\n::: {.cell-output-display}\n![](07-data-insights_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nIf we still see double peaks after subgrouping the data, it suggests that there may be additional underlying factors or patterns within each subgroup that we haven’t accounted for yet. These could be caused by other variables such as age, environmental conditions, or even measurement error, depending on the context of the data.\n\n## Normality\n\nIf our data follows a <a class='glossary'>normal distribution<span class='def'>Also known as the “Gaussian distribution,” it is a probability distribution that is symmetric about the mean, showing that data near the mean are more frequent in occurrence than data far from the mean.</span></a> , we can use just two key metrics — **mean** and **standard deviation** — to predict how the data is spread out and to calculate the probability of observing a specific value. The normal distribution is symmetric and bell-shaped, meaning most data points cluster around the mean, with fewer observations the farther we move from it.\n\n### Why These Measures Matter:\n\n- The <a class='glossary'>mean<span class='def'>The average of a dataset, calculated by summing all values and dividing by the number of observations.</span></a>  gives us a general idea of the \"average\" value, but the <a class='glossary'>standard deviation<span class='def'>A measure of the amount of variation or spread in a dataset, indicating how far data points are from the mean on average.</span></a>  tells us how reliable that mean is by showing how much the data varies around it.\n\n- Together, these two metrics help us understand the overall distribution of a continuous variable. For normally distributed data, roughly 68% of values lie within one standard deviation of the mean, which provides a good sense of the data's spread.\n\n### QQplots\n\nA QQ plot is a useful tool for visually assessing whether a dataset follows a particular distribution, such as the normal distribution. At first glance, QQ plots may look unfamiliar, but they are simple and powerful once you understand the concept.\n\nIn a QQ plot, your sample data is plotted on the y-axis, and the theoretical distribution (often a normal distribution) is plotted on the x-axis. If your data follows a normal distribution, the points in the QQ plot will align along a straight diagonal line. Any deviation from this line indicates that your data departs from the normal distribution, either through skewness, heavy tails, or other irregularities.\n\nHow It Works:\n\n- Data Points on the Y-Axis: These are the actual data values from your sample.\n\n- Theoretical Distribution on the X-Axis: These represent what the data would look like if it perfectly followed a normal distribution.\n\nIf the data aligns well with the theoretical distribution, it forms a straight line. If not, the data will curve away from the line, signaling potential departures from normality.\n\nWatch [this video to see QQ plots explained](https://www.youtube.com/watch?v=okjYjClSjOg) in action and how they help in assessing the distribution of your data!\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(qqplotr)\nggplot(penguins, aes(sample = culmen_length_mm))+\n    stat_qq_band() +\n    stat_qq_line() +\n    stat_qq_point() \n```\n\n::: {.cell-output-display}\n![](07-data-insights_files/figure-html/unnamed-chunk-20-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n### Shapiro test\n\nThe Shapiro-Wilk test is a commonly used statistical test to check whether a dataset follows a normal distribution. It gives a p-value that helps determine if the data significantly deviates from normality. While useful, the Shapiro test has its limitations, especially when it comes to sample size\n\n:::{.callout-warning collapse = \"true\"}\n## Sensitivity to Sample Size: \n\nThe Shapiro-Wilk test is sensitive to sample size. For large samples (> 50), even small deviations from normality can result in significant p-values, leading to a rejection of normality even when the deviations are minor and practically insignificant.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(rstatix)\n\npenguins |> \n  shapiro_test(culmen_length_mm)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|variable         | statistic|        p|\n|:----------------|---------:|--------:|\n|culmen_length_mm | 0.9748548| 1.12e-05|\n\n</div>\n:::\n:::\n\n\nUnlike the Shapiro-Wilk test, a QQ plot provides a visual way to check for normality. It allows you to see exactly how the data deviates from a normal distribution. You can spot patterns such as skewness or heavy tails, which the Shapiro test cannot differentiate.\n\nQQ plots are also more flexible with sample size. They work well with both large and small datasets.\n\n### Normality in subgroups\n\nWhen you analyse the entire dataset as a whole, you are combining different groups—for example, species, locations, or treatments—each of which may have its own distribution. In the Palmer Penguins dataset, bill length and bill depth can differ substantially between species. Testing for normality across the full dataset mixes these distributions, which can give misleading results: you might incorrectly conclude the data are non-normal, or you might miss deviations that exist within individual groups.\n\nBy subgrouping, you can test normality within each group separately. This helps you see whether deviations from normality are common across all groups or specific to certain subgroups, giving a more accurate and interpretable picture of your data. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(qqplotr)\nggplot(penguins, aes(sample = culmen_length_mm))+\n    stat_qq_band() +\n    stat_qq_line() +\n    stat_qq_point() +\n  facet_wrap(~species)\n```\n\n::: {.cell-output-display}\n![](07-data-insights_files/figure-html/unnamed-chunk-22-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |> \n  group_by(species) |> \n  shapiro_test(culmen_length_mm)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|species   |variable         | statistic|         p|\n|:---------|:----------------|---------:|---------:|\n|Adelie    |culmen_length_mm | 0.9933618| 0.7166005|\n|Chinstrap |culmen_length_mm | 0.9752496| 0.1940926|\n|Gentoo    |culmen_length_mm | 0.9727224| 0.0134914|\n\n</div>\n:::\n:::\n\n\nNow we can see that when splitting into species subgroups - that the qqplots are much better. The Shapiro wilk test indicates that the Gentoo population deviates from a normal distribution for bill length, but our qqplot indicates this is very minor and we can still safely use descriptive statistics of mean and standard deviation that rely on this assumption.\n\n## Correlation\n\nA common measure of association between two numerical variables is the correlation coefficient. The correlation metric is a numerical measure of the strength of an association\n\n[Correlation video](https://statquest.org/covariance-and-correlation-part-1-covariance/)\n\nThere are several measures of correlation including:\n\n- **Pearson's correlation coefficient** : good for describing linear associations\n\n- **Spearman's rank correlation coefficient**: a rank ordered correlation - good for when the correlation may not be linear, or the data is not **normally distributed**.\n\nPearson's correlation coefficient `r` is designed to measure the strength of a linear (straight line) association. Pearson's takes a value between -1 and 1.\n\n- A value of 0 means there is no linear association between the variables\n\n- A value of 1 means there is a perfect positive association between the variables\n\n- A value of -1 means there is a perfect negative association between the variables\n\nA perfect association is one where we can predict the value of one variable with complete accuracy, just by knowing the value of the other variable.\n\nWe can use the `rstatix::cor_test()` function in R to calculate Pearson's correlation coefficient.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(rstatix)\n\npenguins |>  \n  cor_test(culmen_length_mm, \n           culmen_depth_mm)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|var1             |var2            |   cor| statistic|        p|   conf.low|  conf.high|method  |\n|:----------------|:---------------|-----:|---------:|--------:|----------:|----------:|:-------|\n|culmen_length_mm |culmen_depth_mm | -0.24| -4.459093| 1.12e-05| -0.3328072| -0.1323004|Pearson |\n\n</div>\n:::\n:::\n\n\nThis tells us two features of the association. It's sign and magnitude. The coefficient is negative, so as bill length increases, bill depth decreases. The value -0.24 indicates a weak negative relationship.\n\nBecause Pearson's coefficient is designed to summarise the strength of a linear relationship, this can be misleading if the relationship is not linear e.g. curved or humped. This is why it's always a good idea to plot the relationship first (see above).\n\nEven when the relationship is linear, it doesn't tell us anything about the steepness of the association (see above). It only tells us how often a change in one variable can predict the change in the other not the value of that change.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/correlation_examples.png){fig-align='center' fig-alt='Correlation examples' width=80%}\n:::\n:::\n\n\nThis can be difficult to understand at first, so carefully consider the figure above.\n\n- The first row above shows differing levels of the strength of association. If we drew a perfect straight line between two variables, how closely do the data points fit around this line.\n\n- The second row shows a series of perfect linear relationships. We can accurately predict the value of one variable just by knowing the value of the other variable, but the steepness of the relationship in each example is very different. This is important because it means a perfect association can still have a small effect.\n\n- The third row shows a series of associations where there is clearly a relationship between the two variables, but it is also not linear so would be inappropriate for a Pearson's correlation.\n\n\n\n### Spearman's rank correlation\n\n:::{.callout-important collapse = \"true\"}\n\n## If the data is not correlated in a straight line (linear), or doesn't have a normal distribution we should use Spearman's over Pearson's\n\nInstead of working with the raw values of our two variables we can use rank ordering instead. The idea is pretty simple if we start with the lowest value in a variable and order it as '1', then assign labels '2', '3' etc. as we ascend in rank order.\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(rstatix)\n\npenguins |> \n  cor_test(culmen_length_mm, \n           culmen_depth_mm,\n           method = \"spearman\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|var1             |var2            |   cor| statistic|        p|method   |\n|:----------------|:---------------|-----:|---------:|--------:|:--------|\n|culmen_length_mm |culmen_depth_mm | -0.22|   8145268| 3.51e-05|Spearman |\n\n</div>\n:::\n:::\n\n\nYou can see that we get a similar *but not identical* estimate of the strength of association. Generally non-parametric tests are less powerful, but have fewer assumptions about the structure of our data.\n\n### Scatterplots\n\nCorrelation coefficients are a quick and simple way to attach a metric to the level of association between two variables. They are limited however in that a single number can never capture the every aspect of their relationship. This is why we visualise our data, and the best way to do that for two continuous variables is to make a scatterplot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nscatterplot <- ggplot(penguins, aes(x= culmen_length_mm, \n                                    y= culmen_depth_mm)) +\n  geom_point()\n\nscatterplot\n```\n\n::: {.cell-output-display}\n![](07-data-insights_files/figure-html/unnamed-chunk-27-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n#### Marginal plots\n\nMarginal plots are useful when you want to explore the distribution of individual variables alongside a scatterplot of the relationship between two variables. They add histograms, density plots, or boxplots to the margins of a scatterplot, providing extra information about the distribution of each variable separately. So we would could add any of the plots we used previously to look at variance in each of our variables `culmen_length_mm` and `culmen_depth_mm`\n\n#### How to Create Marginal Plots: Using patchwork in R\n\n`patchwork` @R-patchwork is an R package that makes it easy to combine multiple ggplots into a single plot layout, including creating layouts for marginal plots. While ggplot2 doesn't natively support marginal plots, patchwork allows you to combine the scatterplot with additional histograms or density plots at the top and side, creating a custom marginal plot.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(patchwork) # package calls should be placed at the TOP of your script\n\nbill_depth_marginal <- penguins |> \n  ggplot()+\n  geom_density(aes(x=culmen_depth_mm), fill=\"darkgrey\")+\n  theme_void()+\n  coord_flip() # this graph needs to be rotated\n\nbill_length_marginal <- penguins |> \n  ggplot()+\n  geom_density(aes(x=culmen_length_mm), fill=\"darkgrey\")+\n  theme_void()\n\nlayout <- \"\nAA#\nBBC\nBBC\"\n\n# layout is easiest to organise using a text distribution, where ABC equal the three plots in order, and the grid is how much space they take up. We could easily make the main plot bigger and marginals smaller with\n\nscatterplot <- scatterplot +\n  geom_smooth(method = \"lm\",\n              se = FALSE)\n\nbill_length_marginal+\n  scatterplot+\n  bill_depth_marginal+ \n  # order of plots is important\n  plot_layout(design=layout) \n```\n\n::: {.cell-output-display}\n![](07-data-insights_files/figure-html/unnamed-chunk-28-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n# uses the layout argument defined above to arrange the size and position of plots\n```\n:::\n\n\nFrom this plot we would conclude that there is weak <select class='webex-select'><option value='blank'></option><option value=''>positive</option><option value='answer'>negative</option></select> relationship between culmen length and culmen depth. \n\n\n### GGally\n\nThe R package `GGally` @R-GGally helps us understand the relationships between variables, by producing a pairwise matrix grid made of:\n\n- Scatterplots: The scatterplots in a pairwise matrix (created by `GGally::ggpairs()`) allow you to visually inspect the relationship between pairs of continuous variables. If two variables show a strong linear relationship (points forming a clear diagonal line), it suggests collinearity between those variables.\n\n- Correlation Coefficients: In the pairwise matrix, you can also display correlation coefficients. When these values are close to 1 (positive correlation) or -1 (negative correlation), it suggests that the variables are highly correlated and might indicate collinearity.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(GGally)\n\npenguins |> \n  select(species, \n         island, \n         culmen_length_mm, \n         culmen_depth_mm, \n         flipper_length_mm, \n         body_mass_g, \n         sex) |> \n  ggpairs()\n```\n\n::: {.cell-output-display}\n![](07-data-insights_files/figure-html/unnamed-chunk-29-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nFrom these pairwise plots we can see that there *is* a correlation between flipper length, body mass and the culmen length and depth variables. This is useful information to know when considering the relationship between variables for cause and effect, and will be important when build statistical models. \n\n:::{.callout-important collapse=\"true\"}\n\n### Applying Subgroups in GGally\n\nSince GGally builds on ggplot2, you can apply the same customisations that ggplot2 allows, including the use of color to represent different subgroups in your data. This is especially useful when exploring relationships between variables, as it helps highlight patterns or differences between categories (e.g., species, sex, or location).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |> \n  ggpairs(columns = c(\n         \"island\", \n         \"culmen_length_mm\", \n         \"culmen_depth_mm\", \n         \"flipper_length_mm\", \n         \"body_mass_g\", \n         \"sex\"), \n         ggplot2::aes(colour = species))\n```\n\n::: {.cell-output-display}\n![](07-data-insights_files/figure-html/unnamed-chunk-30-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\nWhy is this useful? It means we can identify group-specific trends: Adding colour based on a categorical variable (like species) helps you quickly spot trends or patterns that may exist only within certain groups.\n\n:::\n\n## Thinking Causally: Interpreting Relationships Carefully\n\nSo far we have described patterns (distribution, correlation). Causal thinking adds one disciplined question:\n\n> Could another variable explain, mask, change, or reverse the relationship we see between two variables?\n\nWe will NOT “prove” causation here. Instead we (a) name the main structures that can mislead, and (b) practice simple checks.\n\n### Core Terms \n\n| Term | Meaning | Penguin example |\n|------|----------------------|-----------------|\n| Association | Two variables vary together | Culmen length & culmen depth correlate |\n| Confounder | Variable that influences *both* variables of interest, creating a misleading pooled pattern | Species affects both length and depth |\n| Omitted variable bias | Distortion in a relationship caused by leaving out a confounder | Ignoring species when correlating length & depth |\n| Effect modifier/moderator (interaction) | A variable that changes the *strength or slope* of a relationship | sex might change the slope of length→depth (if slopes differ) |\n| Simpson’s paradox | Pooled trend weakens/reverses after stratifying by a confounder | Pooled weak/negative vs within‑species positive |\n| Adjustment / Stratification | Looking within levels (or controlling for) a variable (e.g. species) | Facet by species |\n| DAG (Directed Acrylic Graph) | A simple arrow diagram of assumptions | species → length; species → depth; length → depth (?) |\n\n\n\n### Example DAG\n\nWe hypothesise that:\n\n```\nspecies → culmen_length_mm\nspecies → culmen_depth_mm\nsex → culmen_depth_mm   (maybe sex → culmen_length_mm)\nculmen_length_mm → culmen_depth_mm ?   (relationship we are exploring)\n```\n\nInterpretation:\n- Species is a **confounder** of length–depth as it can affect both *directly*\n- Sex might weakly confound or modify (check visually).\n- We “adjust” by stratifying (faceting, colouring etc.) or adding grouping to summaries.\n\n\n### Checklist Before Interpreting a Scatterplot\n\n1. Are there obvious grouping variables that should have been included? (species, sex, island)\n2. Does the pooled relationship differ visually from within-group lines?\n3. Do group slopes look similar (association consistent) or different (effect modification)?\n4. Did missing values drop particular groups (re-check small `n`)?\n5. After splitting by groups, does the direction/strength change (Simpson’s paradox)?\n\n#### Activity: Revisit the Pooled Plot\n\n(You likely have this already—repeat quickly.)\n\n\n<div class='webex-solution'><button>Pooled plot</button>\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(penguins, aes(culmen_length_mm, culmen_depth_mm)) +\n  geom_point(alpha = 0.6) +\n  geom_smooth(method=\"lm\", se=FALSE, colour=\"black\") +\n  labs(x=\"Culmen length (mm)\", y=\"Culmen depth (mm)\")\n```\n\n::: {.cell-output-display}\n![](07-data-insights_files/figure-html/unnamed-chunk-31-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n</div>\n\n\nQuestion: Is the pooled slope clearly positive, clearly negative, or weak/ambiguous?\n\n<select class='webex-select'><option value='blank'></option><option value=''>strong positive</option><option value='answer'>strong negative</option><option value=''>weak positive</option><option value=''>weak negative</option></select>\n\n\n#### Activity: Split by Species (Confounding Check)\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncolours <- c(\"cyan\",\n             \"darkorange\",\n             \"purple\")\n\nscatterplot_2 <- ggplot(penguins, aes(x= culmen_length_mm, \n                     y= culmen_depth_mm,\n                     colour=species)) +\n    geom_point()+\n  geom_smooth(method=\"lm\",\n              se=FALSE)+\n  scale_colour_manual(values=colours)+\n  theme_classic()+\n  theme(legend.position=\"none\")+\n    labs(x=\"Bill length (mm)\",\n         y=\"Bill depth (mm)\")\n\nbill_depth_marginal_2 <- penguins |> \n  ggplot()+\n  geom_density(aes(x=culmen_depth_mm,\n                   fill=species),\n               alpha=0.5)+\n  scale_fill_manual(values=colours)+\n  theme_void()+\n  coord_flip() # this graph needs to be rotated\n\nbill_length_marginal_2 <- penguins |> \n  ggplot()+\n  geom_density(aes(x=culmen_length_mm,\n                   fill=species),\n               alpha=0.5)+\n  scale_fill_manual(values=colours)+\n  theme_void()+\n  theme(legend.position=\"none\")\n\nlayout2 <- \"\nAAA#\nBBBC\nBBBC\nBBBC\"\n\nbill_length_marginal_2+scatterplot_2+bill_depth_marginal_2+ # order of plots is important\n  plot_layout(design=layout2) # uses the layout argument defined above to arrange the size and position of plots\n```\n\n::: {.cell-output-display}\n![](07-data-insights_files/figure-html/unnamed-chunk-32-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n</div>\n\n\nTask:\n\n1. Visually compare each species’ slope to the pooled one.\n\n2. If pooled and within-species slopes differ in sign or strength, species is a confounder (Simpson’s paradox manifested).\n\nSpecies IS a confounder <select class='webex-select'><option value='blank'></option><option value='answer'>TRUE</option><option value=''>FALSE</option></select>\n\n#### Activity: Add Sex as a Potential Effect Modifier\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(penguins |> drop_na(sex),\n       aes(culmen_length_mm, culmen_depth_mm,\n           colour = sex)) +\n  geom_point(alpha=0.5) +\n  geom_smooth(method=\"lm\", se=FALSE) +\n  facet_wrap(~ species) +\n  labs(x=\"Culmen length (mm)\", y=\"Culmen depth (mm)\",\n       colour=\"Sex\")\n```\n\n::: {.cell-output-display}\n![](07-data-insights_files/figure-html/unnamed-chunk-33-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n</div>\n\n\nTask:\n\n- Do male vs female slopes *within the same species* look meaningfully different?  \n  \n  - If yes, sex may be an effect modifier.  \n  \n  - If not, treat sex mainly as a potential (minor) confounder or even ignore for this relationship.\n\n#### Exercise 4: Correlation Contrast (Quantify the Change)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Pooled\npenguins |>\n  cor_test(culmen_length_mm, culmen_depth_mm)\n\n# By species\npenguins |>\n  group_by(species) |>\n  cor_test(culmen_length_mm, culmen_depth_mm)\n\n# By species & sex (only if enough rows)\npenguins |>\n  filter(!is.na(sex)) |>\n  group_by(species, sex) |>\n  summarise(n = n()) |>\n  arrange(n)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|var1             |var2            |   cor| statistic|        p|   conf.low|  conf.high|method  |\n|:----------------|:---------------|-----:|---------:|--------:|----------:|----------:|:-------|\n|culmen_length_mm |culmen_depth_mm | -0.24| -4.459093| 1.12e-05| -0.3328072| -0.1323004|Pearson |\n\n</div><div class=\"kable-table\">\n\n|species   |var1             |var2            |  cor| statistic|     p|  conf.low| conf.high|method  |\n|:---------|:----------------|:---------------|----:|---------:|-----:|---------:|---------:|:-------|\n|Adelie    |culmen_length_mm |culmen_depth_mm | 0.39|  5.193285| 7e-07| 0.2472226| 0.5187796|Pearson |\n|Chinstrap |culmen_length_mm |culmen_depth_mm | 0.65|  7.014647| 0e+00| 0.4917326| 0.7717134|Pearson |\n|Gentoo    |culmen_length_mm |culmen_depth_mm | 0.64|  9.244703| 0e+00| 0.5262952| 0.7365271|Pearson |\n\n</div><div class=\"kable-table\">\n\n|species   |sex    |  n|\n|:---------|:------|--:|\n|Chinstrap |Female | 34|\n|Chinstrap |Male   | 34|\n|Gentoo    |Female | 58|\n|Gentoo    |Male   | 61|\n|Adelie    |Female | 73|\n|Adelie    |Male   | 73|\n\n</div>\n:::\n:::\n\n\nTask:\n\n- Confirm each species’ correlation is stronger and (likely) positive.\n\n- Check counts before splitting further by sex -  low `n` makes interpretations less certain.\n\n#### Exercise 5 (Optional): “What if Island?”\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins |>\n  count(island, species)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|island    |species   |   n|\n|:---------|:---------|---:|\n|Biscoe    |Adelie    |  44|\n|Biscoe    |Gentoo    | 124|\n|Dream     |Adelie    |  56|\n|Dream     |Chinstrap |  68|\n|Torgersen |Adelie    |  52|\n\n</div>\n:::\n:::\n\n\nTask:\n\n- If one species is almost exclusive to an island, island adds little *additional* confounding once species is in the picture. Make a one-line note.\n\n---\n\n### Interpretation Templates\n\nPick one that matches what you observe:\n\n1. *Confounding only:*  \n   “Species confounds the culmen length–depth relationship: pooled association was weak, but each species shows a clear positive trend.”\n\n2. *Confounding + minor effect modification:*  \n   “Species confounds and slightly modifies the relationship: all species show positive slopes, but Chinstrap is steeper.”\n\n3. *No strong modification:*  \n   “After adjusting for species, the length–depth association is consistently positive with similar slopes, suggesting little effect modification by species.”\n\n4. *Sex modifies (if evident):*  \n   “Within species, male and female slopes differ (Gentoo largest gap), indicating sex may modify the length–depth relationship.”\n\n---\n\n### Rapid Reflection (Write 1–2 Sentences Each)\n\n1. Which variable had the strongest confounding impact? Why?\n2. Did any variable *change* (modify) slope shape, or did it only shift intercepts?\n3. Which additional variable would you next test and why (island, year, body_mass_g, flipper_length_mm)?\n4. Provide a final adjusted interpretation (choose or adapt a template).\n\n\n<div class='webex-solution'><button>Example Answer</button>\n\nSpecies was the key confounder: pooled slope understated the positive within-species scaling. Slopes were similar across sexes, so sex isn’t a strong effect modifier here. I would next inspect body_mass_g because it correlates with both bill dimensions and could enter a future multivariable model.\n\n</div>\n\n\n---\n\n### Causal Mini‑Summary\n\n- Start from a pattern (association).  \n- Ask: “Could a third variable explain or change this pattern?” (confounder or modifier).  \n- Stratify or adjust.  \n- Compare pooled vs stratified results.  \n- Report the adjusted story, not the misleading pooled one.\n\n\n\n## Summary\n\nGood exploratory analysis is more than generating a gallery of plots. Follow a clear workflow: summarise → visualise → think causally.\n\n1. Summarise: Compute core descriptive statistics (counts, mean/median, sd/IQR) overall and by biologically relevant groups (species, sex).\n\n2. Visualise: Use complementary plot types (histograms + density, box + violin, scatter + stratified regression lines) to uncover shape, variation, multigroup structure, and potential outliers.\n\n3. Think Causally: Ask whether apparent associations (e.g. culmen length vs depth) could be explained by confounders (species) or modified by other variables (sex). Stratify early to prevent misinterpretation (Simpson’s paradox).\n\nAlong the way:\n\n- Inspect group balance (are some islands or species overrepresented?).\n\n- Handle missing data transparently (avoid silent bias from complete-case filtering).\n\n- Flag strongly correlated predictors for later modelling choices.\n\n- Distinguish “association” from a causal story; visual adjustments (colouring/faceting) are informal “adjustments.”\n\n- Use concise interpretation templates: report the adjusted relationships, not just the pooled one.\n\nEnd every exploration by answering:\n\n- What changed after grouping/splitting?\n\n- Which variables mattered most?\n\n- What uncertainties remain?\n\nA high-quality summary is a short, justified narrative linking observed patterns to biological structure—not a disconnected sequence of figures.\n\n\n## Glossary\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:left;\"> definition </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> bias </td>\n   <td style=\"text-align:left;\"> A systematic error or distortion in data collection or analysis that leads to inaccurate conclusions or results. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> boxplot </td>\n   <td style=\"text-align:left;\"> A compact visual summary of a datasets distribution, showing the median, interquartile range (IQR), and outliers. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> confounding variable </td>\n   <td style=\"text-align:left;\"> A variable that affects both the independent and dependent variables, potentially distorting the observed relationship between them. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> correlation coefficient </td>\n   <td style=\"text-align:left;\"> A numerical value ranging from -1 to 1 that measures the strength and direction of the linear relationship between two variables. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> density plots </td>\n   <td style=\"text-align:left;\"> A density plot is a visualization of the distribution of a continuous numerical variable, acting as a smoothed, continuous version of a histogram. It uses a mathematical technique called kernel density estimation to draw a smooth curve that estimates the probability distribution of the data, making it easier to see the underlying shape and overall pattern compared to a histogram </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> histogram </td>\n   <td style=\"text-align:left;\"> A graphical representation of the distribution of a dataset by grouping data into bins and showing the frequency of observations within each bin. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> mean </td>\n   <td style=\"text-align:left;\"> The average of a dataset, calculated by summing all values and dividing by the number of observations. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> normal distribution </td>\n   <td style=\"text-align:left;\"> Also known as the \"Gaussian distribution,\" it is a probability distribution that is symmetric about the mean, showing that data near the mean are more frequent in occurrence than data far from the mean. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> outliers </td>\n   <td style=\"text-align:left;\"> Data points that are significantly different from the rest of the dataset, often lying far from the median or mean. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> scatterplots </td>\n   <td style=\"text-align:left;\"> A graph that displays the relationship between two numerical variables by plotting data points on an X and Y axis. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> standard deviation </td>\n   <td style=\"text-align:left;\"> A measure of the amount of variation or spread in a dataset, indicating how far data points are from the mean on average. </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## Reading\n\n- [A protocol for data exploration to avoid common statistical problems](https://doi.org/10.1111/j.2041-210X.2009.00001.x)\n",
    "supporting": [
      "07-data-insights_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}