# Overview {.unnumbered}

This course will introduce scientists and practitioners interested in applying statistical approaches in their daily routine using R as a working environment. Participants will be introduced into R and R Studio while learning how to perform common statistical analyses. After a short introduction on R and its principles, the focus will be on questions that could be addressed using common statistical analyses, both for descriptive statistics and for statistical inference.

## Learning outcomes

- Understand how to read, interpret and write scripts in R.

- Learn how to check and clean data 

- Learn statistical tools to address common questions in research activities.

- An introduction to efficient, readable and reproducible analyses

- Being comfortable with using R when performing both descriptive and inferential statistics.


## How to use this book
For many of the chapters, we will provide the code you need to use. You can copy and paste from the book using the clipboard in the top-right corner.

We also provide the solutions to many of the activities. No-one is going to check whether you tried to figure it out yourself rather than going straight to the solution but remember this: if you copy and paste without thinking, you will learn nothing.

Finally, on occasion we will make updates to the book such as fixing typos and including additional detail or activities and as such this book should be considered a living document. Please tell me if you find any mistakes.

##  Course Structure

We have:

- One **workshop per week**, these both timetabled in-person sessions, and you should check Timetabler for up to-date information on scheduling. However, everything you need to complete workshops will be available on this site.

    - If you feel unwell, or cannot attend a session in-person don’t worry you can access everything, and follow along in real time, or work at your own pace.

- One **assignment per week** - this will be in the form of quizzes or short assignments, each assignment is worth 2% of your module grade (to a maximum of 15%) and there will be 10 assignments total.

- One **data analysis project** - this will be a single piece of coursework (details after reading week) worth 20% of the the module grade 



```{r cite-packages, include = FALSE}
# automatically create a bib database for R packages
# add any packages you want to cite here
knitr::write_bib(c(
  .packages(), 'rstatix', 'patchwork', 'here', 'kableExtra', 'plotly', 'gitcreds', 'usethis', 'ggridges', 'scales', 'purrr', 'tinytex', 'gt', 'broom', 'tidyverse', 'rstatix', 'performance', 'see', 'lme4', 'lmerTest', 'DHARMa', 'glmmTMB', 'nlme', 'ggeffects', 'sjPlot', 'DHARMa', 'report', 'MuMIn', 'palmerpenguins', 'colorBlindness', 'skimr'
), 'include/packages.bib')


# Set ggplot theme for book
library(ggplot2)


my_theme <- theme_minimal(base_size = 16) + 
  theme(
    panel.grid = element_blank(),  # Removes gridlines
    axis.line = element_line(color = "black")  # Adds x and y axis lines
  )

theme_set(my_theme)

```
