{
  "hash": "a30c94596ebbef54385b52d9f2a671c8",
  "result": {
    "engine": "knitr",
    "markdown": "# Inferential statistics {#sec-stats}\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nIn this chapter will be focusing more on *statistics*. We actually did quite a lot of *descriptive statistics* work previously. Every time we summarised or described our data, by calculating a **mean**, **median**, **standard deviation**, **frequency/count**, or **distribution** we were carrying out *descriptive statistics* that helped us understand our data better. \n\nWe are building on this to develop our skills in *inferential statistics*. Inferential statistics allow us to make generalisations - taking a descriptive statistics from our data such as the **sample mean**, and using it to say something about a population parameter (i.e. the **population mean**).\n\nFor example we might measure the measure the heights of some plants that have been outcrossed and inbred and make some summaries and figures to construct an average difference in height (this is **descriptive**). Or we could use this to produce some estimates of the general effect of outcrossing vs inbreeding on plant heights (this is **inferential**). \n\n\n## Darwin's maize data\n\nLoss of genetic diversity is an important issue in the conservation of species. Declines in population size due to over exploitation, habitat fragmentation lead to loss of genetic diversity. Even populations restored to viable numbers through conservation efforts may suffer from continued loss of population fitness because of inbreeding depression.\n\nCharles Darwin even wrote a book on the subject *\"The Effects of Cross and Self-Fertilisation in the Vegetable Kingdom\"*. In this he describes how he produced seeds of maize (*Zea mays*) that were fertilised with pollen from the same individual or from a different plant. The height of the seedlings that were produced from these were then measured as a proxy for their evolutionary fitness.\n\nDarwin wanted to know whether inbreeding reduced the fitness of the selfed plants - this was his **hypothesis**. The data we are going to use today is from Darwin's original dataset.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<a href=\"https://raw.githubusercontent.com/UEABIO/data-sci-v1/main/book/files/darwin.csv\">\n<button class=\"btn btn-success\"><i class=\"fa fa-save\"></i> Download Maize data as csv</button>\n</a>\n```\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(here)\n\ndarwin <- read_csv(here(\"data\", \"darwin.csv\"))\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n:::{.callout-important}\n\nSet up a new project\n\nHave you got separate subfolders set up within your project? \n\nYou should set up a script to put your work into - use this to write instructions and store comments. \n\nUse the File > New Script menu item and select an R Script.\n\n:::\n\n\n### Visualisation\n\nNow seems like a good time for our first data visualisation.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndarwin |> \n  ggplot(aes(x=type,\n         y=height))+\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](08-inferential-statistics_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n# you could also substitute (or combine) other geoms including\n# geom_boxplot()\n# geom_violin()\n# geom_histogram()\n# Why not have a go and see what you can make?\n```\n:::\n\n\nThe graph clearly shows that the average height of the 'crossed' plants is greater than that of the 'selfed' plants. But we need to investigate further in order to determine whether the signal (any apparent differences in mean values) is greater than the level of noise (variance within the different groups). \n\nThe variance appears to be roughly similar between the two groups - though by making a graph we can now clearly see that in the crossed group, there is a *potential* outlier with a value of 12. \n\n### Comparing groups\n\nAs we have seen previously we can use various tidy functions to determine the mean and standard deviations of our groups. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndarwin |> \n  group_by(type) |> \n  summarise(mean=mean(height),\n            sd=sd(height)\n            )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|type  |     mean|       sd|\n|:-----|--------:|--------:|\n|Cross | 20.19167| 3.616945|\n|Self  | 17.57500| 2.051676|\n\n</div>\n:::\n:::\n\n\n\n:::{.callout-tip}\n\nYou should (re)familiarise yourself with how (and why) we calculate standard deviation. \n\n:::\n\n\n## Estimation\n\nIn the section above we concentrated on description. But the hypothesis Darwin aimed to test was whether 'inbreeding reduced the fitness of the selfed plants'. To do this we will use the height of the plants as a proxy for fitness and explicitly address whether there is a **difference** in the mean heights of the plants between these two groups. \n\nOur goal is to: \n\n* Estimate the mean heights of the plants in these two groups\n\n* Estimate the mean *difference* in heights between these two groups\n\n* Quantify our *confidence* in these differences\n\n\n### Standard error\n\nRemember that standard deviation is a descriptive statistic — it measures how much individual data points vary around the mean. In other words, it tells us how spread out our data are within a sample.\n\nHowever, when we move into inferential statistics, we’re no longer just describing our sample — we’re trying to make inferences about the population from which our sample came. This is where the standard error (SE) comes in.\n\nWe can think of the standard error as the standard deviation of the mean. The mean we calculate from our sample is just one possible estimate of the population mean. If we were to repeat our sampling process many times, we’d get slightly different sample means each time. The standard error tells us how much those sample means would typically vary from one sample to another.\n\nIn short, the standard error measures how confident we can be that our sample mean is close to the true population mean.\n\n$$\nSE = \\frac{s}{\\sqrt(n)}\n$$\nwhere\n\n- s = sample standard deviation\n\n- n = sample size\n\nAs sample size increases the standard error should reduce - reflecting an increasing confidence in our estimate. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndarwin |> \n  group_by(type) |> \n  summarise(mean=mean(height),\n            sd=sd(height),\n            n = n(),\n            se = sd/sqrt(n))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|type  |     mean|       sd|  n|        se|\n|:-----|--------:|--------:|--:|---------:|\n|Cross | 20.19167| 3.616945| 15| 0.9338912|\n|Self  | 17.57500| 2.051676| 15| 0.5297405|\n\n</div>\n:::\n:::\n\n\nHere is a great explainer video on [Standard Error](https://www.youtube.com/watch?v=A82brFpdr9g)\n\nAnd try this [Shiny App on Sampling](http://pleft86.shinyapps.io/Sampling)\n\n### Standard error of the difference\n\nJust as the standard error tells us how much a single sample mean would vary across repeated samples, the standard error of the difference tells us how much the **difference** between two sample means would vary if we repeated the experiment many times.\n\nWhen comparing two groups (for example, two plant treatments), each sample mean has its own sampling variability. The variability in the difference between those means depends on both standard errors:\n\n$$\nSE_{diff} = \\sqrt{SE^2_1 + SE^2_2}\n$$\n\nThis combined standard error forms the basis for inferential tests like the t-test, where we assess whether the observed difference between two means is likely due to random sampling variation — or reflects a real difference in the populatio\n\nOur estimate of the mean is not really very useful without an accompanying measuring of *uncertainty* like the standard error, in fact estimates of averages or differences should **always** be accompanied by their measure of uncertainty. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nse_diff <- darwin |> \n  group_by(type) |> \n  summarise(\n    mean = mean(height),\n    sd = sd(height),\n    n = n(),\n    se = sd / sqrt(n)\n  ) |> \n  summarise(\n    mean_diff = diff(mean), \n    se_diff = sqrt(sum(se^2))\n  )\n\nse_diff\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| mean_diff|  se_diff|\n|---------:|--------:|\n| -2.616667| 1.073675|\n\n</div>\n:::\n:::\n\n\n\n### Normal distribution\n\nThe **normal distribution** describes data that form a **bell-shaped curve** when plotted on a graph. Most values are close to the **mean** (average), and fewer occur as you move further away from it in either direction.\n\n[What is the normal distribution](https://www.youtube.com/watch?v=rzFX5NWojp0&t=2s)\n\n### Spread of the data\n\nThe standard deviation measures how spread out the data are from the mean:\n\n- A small standard deviation → data are close to the mean → tall, narrow curve.\n\n- A large standard deviation → data are more spread out → wide, flat curve.\n\nThe bell-shaped curve appears often in nature — for example, in human height, penguin flipper length, or plant height.\n\nAs a probability distribution, the total area under the curve equals 1 (the whole population). Certain parts of the curve correspond to known probabilities:\n\n- About 68% of values are within 1 standard deviation of the mean.\n\n- About 95% are within 2 standard deviations.\n\n- About 99.7% are within 3 standard deviations.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-inferential-statistics_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n#### The Central Limit Theorem\n\nThe **central limit theorem** tells us that if we take many random samples from a population, the averages (sample means) will form a normal distribution — even if the original data are not normal.\n\nThe **standard error (SE)** shows how much the sample mean varies from the true population mean.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-inferential-statistics_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n#### Example: Comparing Plant Heights\n\nSuppose we measure the difference in height between two groups of maize plants — cross-pollinated and self-pollinated.\nWe find a mean difference of 2.62 inches, with a standard error of 1.07 inches.\n\nIf the true difference between the groups were actually zero, how likely would it be to observe a difference of 2.62 inches?\n\nBecause 2.62 is more than two standard errors from zero, it would be unusual to see this by chance alone. That’s why we might reject the null hypothesis (that there’s no difference).\nIn statistical terms, this corresponds to a p-value < 0.05.\n\nIf we used a stricter test (for example, p < 0.001), the result would not be considered significant, since zero would still fall within three standard errors.\n\n### Confidence Intervals\n\nA confidence interval (CI) gives a range that is likely to include the true mean difference.\n\nSince ±2 standard errors cover about 95% of the normal curve, the 95% confidence interval for our estimate is:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlowerCI <- 2.62-(2*1.07)\n\nupperCI <- 2.62+(2*1.07)\n\nlowerCI\nupperCI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.48\n[1] 4.76\n```\n\n\n:::\n:::\n\n\nSo, we write this as:\n\n\n:::{.callout-tip}\n\nThe maize plants that have been cross pollinated were taller on average than the self-pollinated plants, with a mean difference in height of 2.62 [0.18, 5.06] inches (mean [95% CI]).\n\n:::\n\nThis statement clearly shows the direction, size, and uncertainty of the difference.\n\n> It’s a common mistake to say we are 95% sure the true mean lies inside this interval.\nTechnically, it means that if we repeated this experiment many times, 95% of those intervals would contain the true mean.\n\n\n",
    "supporting": [
      "08-inferential-statistics_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/font-awesome-6.5.2/js/script.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}