<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Statistical skills for Biologists">
<title>4&nbsp; Data insights – 5027A</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./r-basics.html" rel="next">
<link href="./06-data-bias.html" rel="prev">
<link href="./images/logos/logo.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
<link rel="stylesheet" href="include/booktem.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/glossary.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07-data-insights.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data insights</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">5027A</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-penguin-project.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Meet the Penguins</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data cleaning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-data-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data bias</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-data-insights.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data insights</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">R Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./projects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Project workflows</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tidy-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Tidy data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#understanding-the-variables" id="toc-understanding-the-variables" class="nav-link active" data-scroll-target="#understanding-the-variables"><span class="header-section-number">4.1</span> Understanding the Variables</a></li>
  <li>
<a href="#what-should-we-consider-in-our-analysis" id="toc-what-should-we-consider-in-our-analysis" class="nav-link" data-scroll-target="#what-should-we-consider-in-our-analysis"><span class="header-section-number">4.2</span> What should we consider in our analysis?</a>
  <ul class="collapse">
<li><a href="#distribution-of-data-types" id="toc-distribution-of-data-types" class="nav-link" data-scroll-target="#distribution-of-data-types"><span class="header-section-number">4.2.1</span> 1. Distribution of Data Types</a></li>
  <li><a href="#central-tendency" id="toc-central-tendency" class="nav-link" data-scroll-target="#central-tendency"><span class="header-section-number">4.2.2</span> 2. Central Tendency</a></li>
  <li><a href="#relationship-between-variables" id="toc-relationship-between-variables" class="nav-link" data-scroll-target="#relationship-between-variables"><span class="header-section-number">4.2.3</span> 3. Relationship Between Variables</a></li>
  <li><a href="#confounding-variables" id="toc-confounding-variables" class="nav-link" data-scroll-target="#confounding-variables"><span class="header-section-number">4.2.4</span> 4. Confounding Variables</a></li>
  <li><a href="#asking-new-questions" id="toc-asking-new-questions" class="nav-link" data-scroll-target="#asking-new-questions"><span class="header-section-number">4.2.5</span> Asking New Questions</a></li>
  <li><a href="#data-checking" id="toc-data-checking" class="nav-link" data-scroll-target="#data-checking"><span class="header-section-number">4.2.6</span> Data checking</a></li>
  </ul>
</li>
  <li>
<a href="#explore-the-distribution-of-categories" id="toc-explore-the-distribution-of-categories" class="nav-link" data-scroll-target="#explore-the-distribution-of-categories"><span class="header-section-number">4.3</span> Explore the distribution of categories</a>
  <ul class="collapse">
<li><a href="#frequency" id="toc-frequency" class="nav-link" data-scroll-target="#frequency"><span class="header-section-number">4.3.1</span> Frequency</a></li>
  <li><a href="#relative-frequency" id="toc-relative-frequency" class="nav-link" data-scroll-target="#relative-frequency"><span class="header-section-number">4.3.2</span> Relative Frequency</a></li>
  </ul>
</li>
  <li><a href="#two-or-more-categories" id="toc-two-or-more-categories" class="nav-link" data-scroll-target="#two-or-more-categories"><span class="header-section-number">4.4</span> Two or more categories</a></li>
  <li>
<a href="#missing-data" id="toc-missing-data" class="nav-link" data-scroll-target="#missing-data"><span class="header-section-number">4.5</span> Missing data</a>
  <ul class="collapse">
<li><a href="#remove-na" id="toc-remove-na" class="nav-link" data-scroll-target="#remove-na"><span class="header-section-number">4.5.1</span> remove na</a></li>
  </ul>
</li>
  <li>
<a href="#continuous-distributions" id="toc-continuous-distributions" class="nav-link" data-scroll-target="#continuous-distributions"><span class="header-section-number">4.6</span> Continuous distributions</a>
  <ul class="collapse">
<li><a href="#summarizing-a-continuous-variable" id="toc-summarizing-a-continuous-variable" class="nav-link" data-scroll-target="#summarizing-a-continuous-variable"><span class="header-section-number">4.6.1</span> Summarizing a Continuous Variable</a></li>
  <li><a href="#histograms" id="toc-histograms" class="nav-link" data-scroll-target="#histograms"><span class="header-section-number">4.6.2</span> Histograms</a></li>
  <li><a href="#boxplots" id="toc-boxplots" class="nav-link" data-scroll-target="#boxplots"><span class="header-section-number">4.6.3</span> Boxplots</a></li>
  </ul>
</li>
  <li>
<a href="#continuous-and-categorical" id="toc-continuous-and-categorical" class="nav-link" data-scroll-target="#continuous-and-categorical"><span class="header-section-number">4.7</span> Continuous and categorical</a>
  <ul class="collapse">
<li><a href="#density-plots" id="toc-density-plots" class="nav-link" data-scroll-target="#density-plots"><span class="header-section-number">4.7.1</span> Density plots</a></li>
  <li><a href="#ggridges" id="toc-ggridges" class="nav-link" data-scroll-target="#ggridges"><span class="header-section-number">4.7.2</span> GGridges</a></li>
  </ul>
</li>
  <li>
<a href="#normality" id="toc-normality" class="nav-link" data-scroll-target="#normality"><span class="header-section-number">4.8</span> Normality</a>
  <ul class="collapse">
<li><a href="#why-these-measures-matter" id="toc-why-these-measures-matter" class="nav-link" data-scroll-target="#why-these-measures-matter"><span class="header-section-number">4.8.1</span> Why These Measures Matter:</a></li>
  <li><a href="#qqplots" id="toc-qqplots" class="nav-link" data-scroll-target="#qqplots"><span class="header-section-number">4.8.2</span> QQplots</a></li>
  <li><a href="#shapiro-test" id="toc-shapiro-test" class="nav-link" data-scroll-target="#shapiro-test"><span class="header-section-number">4.8.3</span> Shapiro test</a></li>
  <li><a href="#normality-in-subgroups" id="toc-normality-in-subgroups" class="nav-link" data-scroll-target="#normality-in-subgroups"><span class="header-section-number">4.8.4</span> Normality in subgroups</a></li>
  </ul>
</li>
  <li>
<a href="#summary-statistics" id="toc-summary-statistics" class="nav-link" data-scroll-target="#summary-statistics"><span class="header-section-number">4.9</span> Summary statistics</a>
  <ul class="collapse">
<li><a href="#calculating-mean-and-standard-deviation" id="toc-calculating-mean-and-standard-deviation" class="nav-link" data-scroll-target="#calculating-mean-and-standard-deviation"><span class="header-section-number">4.9.1</span> Calculating mean and standard deviation</a></li>
  <li><a href="#median-and-quartiles" id="toc-median-and-quartiles" class="nav-link" data-scroll-target="#median-and-quartiles"><span class="header-section-number">4.9.2</span> Median and quartiles</a></li>
  </ul>
</li>
  <li>
<a href="#collinearity" id="toc-collinearity" class="nav-link" data-scroll-target="#collinearity"><span class="header-section-number">4.10</span> Collinearity</a>
  <ul class="collapse">
<li><a href="#ggally" id="toc-ggally" class="nav-link" data-scroll-target="#ggally"><span class="header-section-number">4.10.1</span> GGally</a></li>
  </ul>
</li>
  <li>
<a href="#correlation" id="toc-correlation" class="nav-link" data-scroll-target="#correlation"><span class="header-section-number">4.11</span> Correlation</a>
  <ul class="collapse">
<li><a href="#assumptions-of-pearsons-correlation" id="toc-assumptions-of-pearsons-correlation" class="nav-link" data-scroll-target="#assumptions-of-pearsons-correlation"><span class="header-section-number">4.11.1</span> Assumptions of Pearson’s correlation</a></li>
  <li><a href="#spearmans-rank-correlation" id="toc-spearmans-rank-correlation" class="nav-link" data-scroll-target="#spearmans-rank-correlation"><span class="header-section-number">4.11.2</span> Spearman’s rank correlation</a></li>
  <li><a href="#graphical-summaries-between-numeric-variables" id="toc-graphical-summaries-between-numeric-variables" class="nav-link" data-scroll-target="#graphical-summaries-between-numeric-variables"><span class="header-section-number">4.11.3</span> Graphical summaries between numeric variables</a></li>
  </ul>
</li>
  <li><a href="#important-variables" id="toc-important-variables" class="nav-link" data-scroll-target="#important-variables"><span class="header-section-number">4.12</span> Important variables</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">4.13</span> Summary</a></li>
  <li><a href="#glossary" id="toc-glossary" class="nav-link" data-scroll-target="#glossary"><span class="header-section-number">4.14</span> Glossary</a></li>
  <li><a href="#reading" id="toc-reading" class="nav-link" data-scroll-target="#reading"><span class="header-section-number">4.15</span> Reading</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-insights" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data insights</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>For this exercise, we propose that our task is to generate insights into the relationship between <strong>bill (culmen) length</strong> and <strong>bill (culmen) depth</strong> in penguins. Our goal is to answer the question: <em>Is there a meaningful relationship between these two measurements?</em> Understanding this relationship can provide valuable insights into the physical characteristics of different penguin species and how they may vary.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>You should be working in the script you made in the last session check it contains everything contained in {<a href="05-dplyr.html#sec-save-script" class="quarto-xref"><span>Section 2.6.1</span></a>} and runs without causing errors</p>
</div>
</div>
<section id="understanding-the-variables" class="level2" data-number="4.1"><h2 data-number="4.1" class="anchored" data-anchor-id="understanding-the-variables">
<span class="header-section-number">4.1</span> Understanding the Variables</h2>
<p>Before jumping into the analysis, it’s crucial to take a step back and first understand the variables we’re working with and how they might relate to each other. In this case, our key variables are:</p>
<ul>
<li><p><strong>Culmen Length (bill length)</strong>: This measures the length of the penguin’s bill, an important feature related to feeding.</p></li>
<li><p><strong>Culmen Depth (bill depth)</strong>: This measures the thickness of the penguin’s bill.</p></li>
</ul></section><section id="what-should-we-consider-in-our-analysis" class="level2" data-number="4.2"><h2 data-number="4.2" class="anchored" data-anchor-id="what-should-we-consider-in-our-analysis">
<span class="header-section-number">4.2</span> What should we consider in our analysis?</h2>
<section id="distribution-of-data-types" class="level3" data-number="4.2.1"><h3 data-number="4.2.1" class="anchored" data-anchor-id="distribution-of-data-types">
<span class="header-section-number">4.2.1</span> 1. Distribution of Data Types</h3>
<p>Understanding the type of data we’re dealing with is the first step in any analysis. Both culmen length and depth are continuous numerical variables, meaning they can take a wide range of values. However, our dataset may also include categorical variables like species and island, which will help us group the data and see how these groups influence our measurements.</p>
<p>Why this matters: Knowing whether a variable is numerical or categorical will influence how we visualize it and which statistical methods we use. For instance, numerical data might be plotted using histograms, while categorical data could be displayed using bar charts or boxplots.</p>
</section><section id="central-tendency" class="level3" data-number="4.2.2"><h3 data-number="4.2.2" class="anchored" data-anchor-id="central-tendency">
<span class="header-section-number">4.2.2</span> 2. Central Tendency</h3>
<p>Next, we’ll want to understand the central tendency of our data. Central tendency refers to the average or most common values in a dataset. The mean, median, and mode are common measures used to describe central tendency.</p>
<ul>
<li><p>Mean: The average value (sum of all values divided by the number of values).</p></li>
<li><p>Median: The middle value when data is sorted from lowest to highest, which is especially useful if the data is skewed or contains outliers.</p></li>
<li><p>Mode: The most frequently occurring value in the dataset (not always relevant for continuous data).</p></li>
</ul>
<p>Why this matters: Understanding the average bill length and depth helps us get a sense of what is “normal” for our penguins. Additionally, comparing these statistics across different species or islands could reveal differences in penguin populations.</p>
</section><section id="relationship-between-variables" class="level3" data-number="4.2.3"><h3 data-number="4.2.3" class="anchored" data-anchor-id="relationship-between-variables">
<span class="header-section-number">4.2.3</span> 3. Relationship Between Variables</h3>
<p>Now, we dive into the heart of our analysis: exploring the relationship between culmen length and culmen depth. To investigate this, we can use visual tools like <a class="glossary">scatterplots<span class="def"></span></a> , which allow us to plot one variable against the other and visually check for patterns or trends.</p>
<p>We might also want to calculate a <a class="glossary">correlation coefficient<span class="def">A numerical value ranging from -1 to 1 that measures the strength and direction of the linear relationship between two variables.</span></a> to quantify the strength of the relationship between bill length and bill depth. If we find a strong correlation, we can say that these two measurements tend to move together — for example, as the bill length increases, so might the bill depth.</p>
<p>Why this matters: Identifying the relationship between variables is critical to making meaningful conclusions. If bill length and depth are highly correlated, we can begin to explore why this might be the case — perhaps certain penguin species have distinct bill shapes that differ from others.</p>
</section><section id="confounding-variables" class="level3" data-number="4.2.4"><h3 data-number="4.2.4" class="anchored" data-anchor-id="confounding-variables">
<span class="header-section-number">4.2.4</span> 4. Confounding Variables</h3>
<p>While exploring the relationship between bill length and depth, we must also be aware of the potential impact of <a class="glossary">confounding variable<span class="def">A variable that affects both the independent and dependent variables, potentially distorting the observed relationship between them.</span></a> . A confounding variable is one that influences both the dependent and independent variables, potentially leading to a false conclusion about their relationship.</p>
<p>In this dataset, potential confounders might include:</p>
<ul>
<li><p>Species: Different species may naturally have different bill shapes, so the relationship between culmen length and depth could vary depending on the species.</p></li>
<li><p>Island or Location: Penguins from different islands might experience different environmental pressures that could affect bill size and shape.</p></li>
</ul>
<p>To account for this, we can group or subset the data by species or island and re-examine the relationship between bill length and depth within those groups. This helps us determine if the observed relationship holds true across different groups, or if it is being influenced by these other variables.</p>
<p>Why this matters: Ignoring confounding variables could lead us to incorrect conclusions. For instance, if we see a strong relationship between bill length and depth, it could simply be due to species differences, rather than a true relationship across all penguins.</p>
</section><section id="asking-new-questions" class="level3" data-number="4.2.5"><h3 data-number="4.2.5" class="anchored" data-anchor-id="asking-new-questions">
<span class="header-section-number">4.2.5</span> Asking New Questions</h3>
<p>Every step of the analysis leads to new questions. This is a natural part of the data exploration process. For example:</p>
<ul>
<li><p>After looking at the distribution of culmen length and depth, we might wonder, do certain species have longer bills than others?</p></li>
<li><p>After finding a relationship between the variables, we might ask, is this relationship consistent across different islands or years?</p></li>
<li><p>If we spot outliers, we might ask, why are some penguins’ measurements so different from the rest?</p></li>
</ul></section><section id="data-checking" class="level3" data-number="4.2.6"><h3 data-number="4.2.6" class="anchored" data-anchor-id="data-checking">
<span class="header-section-number">4.2.6</span> Data checking</h3>
<p>Before diving into analysis, it’s crucial to have a clear understanding of the structure and quality of your dataset. This step is part of the data wrangling process and ensures that your data is accurate, clean, and ready for exploration. Key tasks include:</p>
<ul>
<li><p>The number of variables: Know how many variables (columns) are present in the dataset. This helps in understanding the scope of the data and ensuring that all necessary information is available.</p></li>
<li><p>The data format of each variable: Check whether each variable is in the correct format (e.g., numeric, categorical, date). Mistakes in data types, such as a numeric variable being stored as text, can cause errors during analysis.</p></li>
<li><p>Checked for missing data: Identify any missing values and decide how to handle them. Ignoring missing data can skew results, so it’s important to either remove, impute, or investigate why data might be missing.</p></li>
<li><p>Checked for typos, duplications, or other data errors: Manually inspect the data or use automated tools to detect any typos, duplicate entries, or inconsistencies that could impact your analysis. For example, species names should be consistent across all rows.</p></li>
<li><p>Cleaned column or factor names: Ensure that all column names are properly labeled and easy to understand. This includes correcting any typos or formatting issues, such as spaces or special characters in names, which could cause problems when referencing them in code.</p></li>
</ul>
<p>These data checking steps provide a strong foundation for accurate and effective analysis, ensuring that your dataset is reliable and well-structured and luckily we carried this out in {#sec-dplyr}.</p>
</section></section><section id="explore-the-distribution-of-categories" class="level2" data-number="4.3"><h2 data-number="4.3" class="anchored" data-anchor-id="explore-the-distribution-of-categories">
<span class="header-section-number">4.3</span> Explore the distribution of categories</h2>
<p>Understanding how your data is distributed across important grouping variables is essential for context. In this case, the Palmer Penguins dataset includes key groupings such as <strong>species, island, and year</strong>, which might have significant effects on the relationships we want to study (e.g., between bill length and bill depth). By summarizing and visualizing the distribution of these variables, we can ensure that our analyses account for group-level differences, leading to more robust insights.</p>
<section id="frequency" class="level3" data-number="4.3.1"><h3 data-number="4.3.1" class="anchored" data-anchor-id="frequency">
<span class="header-section-number">4.3.1</span> Frequency</h3>
<p>By grouping the data according to the species variable, we can calculate the total count (n) of penguins within each species. This summary provides a clear understanding of how the penguins are distributed across the different species in the dataset. Knowing the sample size for each species is crucial because it informs us about the representation of each group, which affects the reliability of any comparisons or analyses we plan to perform. If one species has far fewer observations than others, for example, it may require special consideration when interpreting results, as smaller sample sizes can lead to less robust conclusions. Understanding this distribution is a foundational step for any further analysis or comparison between species.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb1-2"><a href="#cb1-2"></a>  <span class="co"># calculations applied per species</span></span>
<span id="cb1-3"><a href="#cb1-3"></a>  <span class="fu">group_by</span>(species) <span class="sc">|&gt;</span> </span>
<span id="cb1-4"><a href="#cb1-4"></a>  <span class="co"># summarise the number of observations in each group</span></span>
<span id="cb1-5"><a href="#cb1-5"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: right;">n</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: right;">152</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: right;">68</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: right;">124</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Question</strong> Are there 152 different penguins in our dataset? <select class="webex-select"><option value="blank"></option>
<option value="">TRUE</option>
<option value="answer">FALSE</option></select></p>
<div class="webex-solution">
<button>
Explanation
</button>
<p>The functions above count the number of rows of data - we need to determine if these are repeated or independent measures. We should remember that there is a column called <code>individual_id</code> if we use the <code>n_distinct()</code> function we can count how many unique IDs we have</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb2-2"><a href="#cb2-2"></a>  <span class="co"># calculations applied per species</span></span>
<span id="cb2-3"><a href="#cb2-3"></a>  <span class="fu">group_by</span>(species) <span class="sc">|&gt;</span> </span>
<span id="cb2-4"><a href="#cb2-4"></a>  <span class="co"># summarise the number of observations in each group</span></span>
<span id="cb2-5"><a href="#cb2-5"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n_distinct</span>(individual_id))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: right;">n</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: right;">132</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: right;">58</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: right;">94</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Now we can see that there are only 132 <em>different</em> Adelie penguins in our data</p>
</div>
</section><section id="relative-frequency" class="level3" data-number="4.3.2"><h3 data-number="4.3.2" class="anchored" data-anchor-id="relative-frequency">
<span class="header-section-number">4.3.2</span> Relative Frequency</h3>
<p>In addition to counting the total number of penguins in each species, calculating the relative frequency can be a useful summary. Relative frequency shows the proportion or percentage of observations in each category relative to the total number of observations. This helps us understand not only the absolute count but also how common each species is compared to the others.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>prob_obs_species <span class="ot">&lt;-</span> penguins <span class="sc">|&gt;</span> </span>
<span id="cb3-2"><a href="#cb3-2"></a>  <span class="fu">group_by</span>(species) <span class="sc">|&gt;</span> </span>
<span id="cb3-3"><a href="#cb3-3"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb3-4"><a href="#cb3-4"></a>  <span class="co"># use mutate to make a new column relative frequency</span></span>
<span id="cb3-5"><a href="#cb3-5"></a>  <span class="fu">mutate</span>(<span class="at">prob_obs =</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span>
<span id="cb3-6"><a href="#cb3-6"></a></span>
<span id="cb3-7"><a href="#cb3-7"></a>prob_obs_species</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">prob_obs</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: right;">152</td>
<td style="text-align: right;">0.4418605</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;">0.1976744</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: right;">124</td>
<td style="text-align: right;">0.3604651</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>So about 44% of our sample is made up of observations from Adelie penguins. When it comes to making summaries about categorical data, that’s about the best we can do, we can make observations about the most common categorical observations, and the relative proportions.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb4-2"><a href="#cb4-2"></a>  <span class="fu">mutate</span>(<span class="at">species=</span><span class="fu">fct_relevel</span>(species, </span>
<span id="cb4-3"><a href="#cb4-3"></a>                             <span class="st">"Adelie"</span>,</span>
<span id="cb4-4"><a href="#cb4-4"></a>                             <span class="st">"Gentoo"</span>,</span>
<span id="cb4-5"><a href="#cb4-5"></a>                             <span class="st">"Chinstrap"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb4-6"><a href="#cb4-6"></a>  <span class="co"># set as factor and provide levels</span></span>
<span id="cb4-7"><a href="#cb4-7"></a>  <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb4-8"><a href="#cb4-8"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x=</span>species),</span>
<span id="cb4-9"><a href="#cb4-9"></a>           <span class="at">fill=</span><span class="st">"steelblue"</span>,</span>
<span id="cb4-10"><a href="#cb4-10"></a>           <span class="at">width=</span><span class="fl">0.8</span>)<span class="sc">+</span></span>
<span id="cb4-11"><a href="#cb4-11"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Species"</span>,</span>
<span id="cb4-12"><a href="#cb4-12"></a>       <span class="at">y =</span> <span class="st">"Number of observations"</span>)<span class="sc">+</span></span>
<span id="cb4-13"><a href="#cb4-13"></a>  <span class="fu">geom_text</span>(<span class="at">data=</span>prob_obs_species,</span>
<span id="cb4-14"><a href="#cb4-14"></a>            <span class="fu">aes</span>(<span class="at">y=</span>(n<span class="sc">+</span><span class="dv">10</span>),</span>
<span id="cb4-15"><a href="#cb4-15"></a>                <span class="at">x=</span>species,</span>
<span id="cb4-16"><a href="#cb4-16"></a>                <span class="at">label=</span>scales<span class="sc">::</span><span class="fu">percent</span>(prob_obs)))<span class="sc">+</span></span>
<span id="cb4-17"><a href="#cb4-17"></a>  <span class="fu">coord_flip</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="07-data-insights_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>This is an example of a figure we might use in a report or paper. Having cleaned up the theme, added some simple colour, made sure our labels are clear and descriptive, ordered our categories in ascending frequency order, and included some simple text of percentages to aid readability.</p>
</section></section><section id="two-or-more-categories" class="level2" data-number="4.4"><h2 data-number="4.4" class="anchored" data-anchor-id="two-or-more-categories">
<span class="header-section-number">4.4</span> Two or more categories</h2>
<p>When investigating the distribution of observations, it’s important to consider how other variables might influence this relationship, such as sex, species or observations across years.</p>
<div class="webex-solution">
<button>
Solution
</button>
<p>Understanding how frequency is broken down by island, species year and sex might be useful.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2"></a>  <span class="fu">group_by</span>(island, year, species, sex) <span class="sc">|&gt;</span> </span>
<span id="cb5-3"><a href="#cb5-3"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>()) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">island</th>
<th style="text-align: right;">year</th>
<th style="text-align: left;">species</th>
<th style="text-align: left;">sex</th>
<th style="text-align: right;">n</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">2007</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">2007</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">2007</td>
<td style="text-align: left;">Gentoo</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">2007</td>
<td style="text-align: left;">Gentoo</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">2007</td>
<td style="text-align: left;">Gentoo</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">2008</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">2008</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">2008</td>
<td style="text-align: left;">Gentoo</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">22</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">2008</td>
<td style="text-align: left;">Gentoo</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">23</td>
</tr>
<tr class="even">
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">2008</td>
<td style="text-align: left;">Gentoo</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">2009</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">2009</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">2009</td>
<td style="text-align: left;">Gentoo</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="even">
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">2009</td>
<td style="text-align: left;">Gentoo</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">2009</td>
<td style="text-align: left;">Gentoo</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dream</td>
<td style="text-align: right;">2007</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dream</td>
<td style="text-align: right;">2007</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dream</td>
<td style="text-align: right;">2007</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dream</td>
<td style="text-align: right;">2007</td>
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dream</td>
<td style="text-align: right;">2007</td>
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dream</td>
<td style="text-align: right;">2008</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dream</td>
<td style="text-align: right;">2008</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dream</td>
<td style="text-align: right;">2008</td>
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dream</td>
<td style="text-align: right;">2008</td>
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dream</td>
<td style="text-align: right;">2009</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dream</td>
<td style="text-align: right;">2009</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dream</td>
<td style="text-align: right;">2009</td>
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dream</td>
<td style="text-align: right;">2009</td>
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Torgersen</td>
<td style="text-align: right;">2007</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Torgersen</td>
<td style="text-align: right;">2007</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Torgersen</td>
<td style="text-align: right;">2007</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Torgersen</td>
<td style="text-align: right;">2008</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Torgersen</td>
<td style="text-align: right;">2008</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Torgersen</td>
<td style="text-align: right;">2009</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Torgersen</td>
<td style="text-align: right;">2009</td>
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">8</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a href="#cb6-2"></a>   <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> species,</span>
<span id="cb6-3"><a href="#cb6-3"></a>             <span class="at">fill =</span> sex))<span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4"></a>   <span class="fu">geom_bar</span>(<span class="at">width=</span><span class="fl">0.8</span>,</span>
<span id="cb6-5"><a href="#cb6-5"></a>            <span class="at">position =</span> <span class="fu">position_dodge</span>())<span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Species"</span>,</span>
<span id="cb6-7"><a href="#cb6-7"></a>       <span class="at">y =</span> <span class="st">"Number of observations"</span>)<span class="sc">+</span></span>
<span id="cb6-8"><a href="#cb6-8"></a>  <span class="fu">facet_grid</span>(island <span class="sc">~</span> year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="07-data-insights_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p>By thinking about how categories might interact, we can identify interesting patterns or potential issues that could impact our analysis or data interpretation. Careful consideration of these interactions helps us ensure the validity of our findings. For instance:</p>
<ul>
<li><p>Sex Distribution: Looking at the patterns of male and female penguins, I’m reassured that the number of males and females observed is roughly equal across species and locations. This balance is important because unequal representation of sexes could bias our results, particularly in biological traits like bill length or body mass. Since there’s no imbalance, we can confidently proceed without worrying about gender skewing our insights.</p></li>
<li><p>Species Distribution by Island: There are different numbers of species on different islands, but this variation remains consistent across years. This suggests that the observed species distributions likely reflect true ecological patterns, rather than inconsistencies in data collection. If this trend were erratic across years, we might suspect sampling issues, but the consistency provides confidence in the accuracy of species representation.</p></li>
<li><p>Consistency Across Years: The number of penguins observed is consistent across years, meaning we don’t see major fluctuations in sample size. This consistency is important because significant changes could suggest variations in data collection methods or environmental factors affecting penguin populations. A steady count ensures that any trends or patterns we observe are less likely to be the result of sampling inconsistencies.</p></li>
<li><p>Missing Data for Sex: While there are some missing values for the sex variable, these gaps are small and don’t fit any obvious pattern. This suggests that the missing data is likely random and not linked to a particular species, location, or time period. Since the missing values are few and do not show a clear bias, we can choose to ignore these gaps in the analysis with reasonable confidence that they won’t heavily skew our results.</p></li>
</ul>
<p>By reflecting on these patterns, we can be more confident in the integrity of the data and proceed with analysis, knowing that key variables are well-represented and that any missing data or inconsistencies are minimal and manageable.</p>
</section><section id="missing-data" class="level2" data-number="4.5"><h2 data-number="4.5" class="anchored" data-anchor-id="missing-data">
<span class="header-section-number">4.5</span> Missing data</h2>
<p>In the previous section, we identified some missing data, particularly for the sex variable, and noted that it was relatively small and likely random, meaning we could safely remove it from calculations without concern for <a class="glossary">bias<span class="def">A systematic error or distortion in data collection or analysis that leads to inaccurate conclusions or results.</span></a> . However, when it comes to our variables of interest, such as culmen length and culmen depth, it’s worth taking a closer look at the missing values to understand if they occur in any particular patterns or groupings.</p>
<p>We previously used functions like <code><a href="https://docs.ropensci.org/skimr/reference/skim.html">skimr::skim()</a></code> and <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> to find that there are two missing values each for culmen length and depth. Although this small amount of missing data is unlikely to introduce significant bias, it’s still a good practice to investigate where these missing values are located in the dataset. Identifying patterns or specific groups (e.g., certain species or islands) associated with the missing values can help ensure that the missing data is not clustered in a way that could subtly affect our analysis.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2"></a>  <span class="co"># Filter rows where culmen length is NA</span></span>
<span id="cb7-3"><a href="#cb7-3"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(culmen_length_mm)) <span class="sc">|&gt;</span> </span>
<span id="cb7-4"><a href="#cb7-4"></a>  <span class="co"># Group by species, sex and island</span></span>
<span id="cb7-5"><a href="#cb7-5"></a>  <span class="fu">group_by</span>(species, sex, year, island) <span class="sc">|&gt;</span>                 </span>
<span id="cb7-6"><a href="#cb7-6"></a>  <span class="fu">summarise</span>(<span class="at">n_missing =</span> <span class="fu">n</span>())    </span>
<span id="cb7-7"><a href="#cb7-7"></a></span>
<span id="cb7-8"><a href="#cb7-8"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb7-9"><a href="#cb7-9"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(culmen_depth_mm)) <span class="sc">|&gt;</span>         </span>
<span id="cb7-10"><a href="#cb7-10"></a>  <span class="fu">group_by</span>(species, sex, year, island) <span class="sc">|&gt;</span>               </span>
<span id="cb7-11"><a href="#cb7-11"></a>  <span class="fu">summarise</span>(<span class="at">n_missing =</span> <span class="fu">n</span>())    </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: left;">sex</th>
<th style="text-align: right;">year</th>
<th style="text-align: left;">island</th>
<th style="text-align: right;">n_missing</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">2007</td>
<td style="text-align: left;">Torgersen</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">2009</td>
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: left;">sex</th>
<th style="text-align: right;">year</th>
<th style="text-align: left;">island</th>
<th style="text-align: right;">n_missing</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">2007</td>
<td style="text-align: left;">Torgersen</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">2009</td>
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>There is data missing from one Adelie penguin in 2007 on Torgersen, and one value missing from a Gentoo penguin in 2009 on Biscoe. This is true for both culmen length and depth, it is probably the same penguin in both cases, but how could we change our code to be sure?</p>
<div class="webex-solution">
<button>
Solution
</button>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(culmen_length_mm)) <span class="sc">|&gt;</span> </span>
<span id="cb8-3"><a href="#cb8-3"></a><span class="co"># ADD individual id into group_by arguments</span></span>
<span id="cb8-4"><a href="#cb8-4"></a>  <span class="fu">group_by</span>(species, sex, year, island, individual_id) <span class="sc">|&gt;</span>                 </span>
<span id="cb8-5"><a href="#cb8-5"></a>  <span class="fu">summarise</span>(<span class="at">n_missing =</span> <span class="fu">n</span>())    </span>
<span id="cb8-6"><a href="#cb8-6"></a></span>
<span id="cb8-7"><a href="#cb8-7"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb8-8"><a href="#cb8-8"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(culmen_depth_mm)) <span class="sc">|&gt;</span>         </span>
<span id="cb8-9"><a href="#cb8-9"></a>  <span class="fu">group_by</span>(species, sex, year, island, individual_id) <span class="sc">|&gt;</span>               </span>
<span id="cb8-10"><a href="#cb8-10"></a>  <span class="fu">summarise</span>(<span class="at">n_missing =</span> <span class="fu">n</span>())    </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: left;">sex</th>
<th style="text-align: right;">year</th>
<th style="text-align: left;">island</th>
<th style="text-align: left;">individual_id</th>
<th style="text-align: right;">n_missing</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">2007</td>
<td style="text-align: left;">Torgersen</td>
<td style="text-align: left;">N2A2</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">2009</td>
<td style="text-align: left;">Biscoe</td>
<td style="text-align: left;">N38A2</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: left;">sex</th>
<th style="text-align: right;">year</th>
<th style="text-align: left;">island</th>
<th style="text-align: left;">individual_id</th>
<th style="text-align: right;">n_missing</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">2007</td>
<td style="text-align: left;">Torgersen</td>
<td style="text-align: left;">N2A2</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">2009</td>
<td style="text-align: left;">Biscoe</td>
<td style="text-align: left;">N38A2</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>Again here we could safely drop these from our data and regard these as missing at random.</p>
<section id="remove-na" class="level3" data-number="4.5.1"><h3 data-number="4.5.1" class="anchored" data-anchor-id="remove-na">
<span class="header-section-number">4.5.1</span> remove na</h3>
<p>If we are confident that missing data is not causing bias, then there are a few different ways we can deal with missing data so that it doesn’t affect our calculations:</p>
<section id="drop_na-on-everything-before-we-start." class="level4" data-number="4.5.1.1"><h4 data-number="4.5.1.1" class="anchored" data-anchor-id="drop_na-on-everything-before-we-start.">
<span class="header-section-number">4.5.1.1</span> <code>drop_na()</code> on everything before we start.</h4>
<p>Using drop_na() to remove rows that contain any missing values across all variables can be useful, but it also runs the risk of losing a large portion of the data.</p>
<ul>
<li><p>Pros: It’s a simple, all-in-one solution for datasets where missing values are widespread and problematic.</p></li>
<li><p>Cons: This method may remove entire rows of data, even if the missing value is only in a single, unimportant column. This can lead to significant data loss if many rows have missing values in non-critical variables.</p></li>
</ul></section><section id="drop_na-on-a-particular-variable." class="level4" data-number="4.5.1.2"><h4 data-number="4.5.1.2" class="anchored" data-anchor-id="drop_na-on-a-particular-variable.">
<span class="header-section-number">4.5.1.2</span> <code>drop_na()</code> on a particular variable.</h4>
<p>Another approach is to remove rows with missing data in a specific variable, such as <code>body_mass_g</code>. This is less drastic but still needs to be done thoughtfully, especially if you overwrite the original dataset with the modified version. It’s often better to drop <code>NA</code>s temporarily for specific analyses or calculations.</p>
<ul>
<li><p>Pros: You retain more data because you only remove rows with missing values in the column that matters for your current analysis.</p></li>
<li><p>Cons: You might still lose useful information from other columns. If you overwrite the dataset permanently (e.g., using <code>penguins &lt;- penguins |&gt; drop_na(body_mass_g))</code>, you can’t recover the dropped rows without reloading the data.</p></li>
</ul></section><section id="use-arguments-inside-functions" class="level4" data-number="4.5.1.3"><h4 data-number="4.5.1.3" class="anchored" data-anchor-id="use-arguments-inside-functions">
<span class="header-section-number">4.5.1.3</span> Use arguments inside functions</h4>
<p>A more cautious approach is to handle missing data within summary or calculation functions, using the <code>na.rm = TRUE</code> argument. Many summary functions (like <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code>, <code><a href="https://rdrr.io/r/stats/median.html">median()</a></code>, or <code><a href="https://rdrr.io/r/base/sum.html">sum()</a></code>) include this argument, which, when set to <code>TRUE</code>, excludes <code>NA</code> values from the calculation. This allows you to keep missing values in the dataset but ignore them only when performing calculations.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a href="#cb9-2"></a>  <span class="fu">summarise</span>(</span>
<span id="cb9-3"><a href="#cb9-3"></a>    <span class="at">mean_body_mass =</span> <span class="fu">mean</span>(body_mass_g, <span class="at">na.rm =</span> T)</span>
<span id="cb9-4"><a href="#cb9-4"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p>Pros: This is the least destructive option because it allows you to handle missing data without removing any rows from the dataset. You only exclude <code>NA</code> values during specific calculations.</p></li>
<li><p>Cons: This doesn’t remove missing data, so you need to ensure that they won’t cause issues later in other analyses (e.g., regressions or visualizations).</p></li>
</ul></section></section></section><section id="continuous-distributions" class="level2" data-number="4.6"><h2 data-number="4.6" class="anchored" data-anchor-id="continuous-distributions">
<span class="header-section-number">4.6</span> Continuous distributions</h2>
<p>A continuous variable is a type of numerical variable that can take an infinite number of values within a given range. Unlike categorical variables, which represent distinct groups or categories, continuous variables can represent quantities that can be measured with fine precision. Examples include height, weight, temperature, or in the case of the Palmer Penguins dataset, culmen length and culmen depth.</p>
<section id="summarizing-a-continuous-variable" class="level3" data-number="4.6.1"><h3 data-number="4.6.1" class="anchored" data-anchor-id="summarizing-a-continuous-variable">
<span class="header-section-number">4.6.1</span> Summarizing a Continuous Variable</h3>
<p>To summarize a continuous variable, we typically focus on two key aspects:</p>
<ul>
<li><p><a class="glossary">central tendency<span class="def">A statistical measure that identifies the center or typical value in a dataset, often represented by the mean, median, or mode.</span></a> (such as the mean)</p></li>
<li><p><a class="glossary">variation<span class="def">A measure of how spread out or dispersed the data points are in relation to each other or the central value.</span></a> (such as standard deviation)</p></li>
</ul>
<section id="mean-central-tendency" class="level4" data-number="4.6.1.1"><h4 data-number="4.6.1.1" class="anchored" data-anchor-id="mean-central-tendency">
<span class="header-section-number">4.6.1.1</span> Mean (Central Tendency)</h4>
<p>The mean is the average value of a continuous variable. It is calculated by summing all the values and then dividing by the number of observations. The mean gives us a sense of the central location of the data, or where most of the data points cluster around.</p>
<ul>
<li>Example: The mean culmen length of penguins gives us an average bill length, which represents the central value of the dataset.</li>
</ul></section><section id="variation-spread" class="level4" data-number="4.6.1.2"><h4 data-number="4.6.1.2" class="anchored" data-anchor-id="variation-spread">
<span class="header-section-number">4.6.1.2</span> Variation (Spread)</h4>
<p>Variation describes how spread out the data points are around the mean.</p>
<p>This concept is critical in data analysis because every variable exhibits its own unique pattern of variation. Understanding these patterns can provide important insights into the data. For example, the variation in penguin body mass or bill length across different species may reveal ecological or biological differences that are crucial to your analysis.</p>
<p>The best way to explore and understand the pattern of variation is by visualizing the distribution of the variable’s values. By plotting histograms, boxplots, or density plots, you can observe how the data is spread out, whether it is concentrated around a central value, or if there are any outliers. These visualizations allow you to quickly identify the extent of variation and gain insights into the behavior of the variable.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the examples below I will look at the distributions of culmen length, you should modify and duplicate the code so that you check both culmen length and culmen depth.</p>
</div>
</div>
</section></section><section id="histograms" class="level3" data-number="4.6.2"><h3 data-number="4.6.2" class="anchored" data-anchor-id="histograms">
<span class="header-section-number">4.6.2</span> Histograms</h3>
<p>This is the script to plot a frequency distribution, we only specify an x variable, because we intend to plot a <a class="glossary">histogram<span class="def">A graphical representation of the distribution of a dataset by grouping data into bins and showing the frequency of observations within each bin.</span></a> , and the y variable is always the count of observations. Here we ask the data to be presented in 10 equally sized bins of data. In this case chopping the x axis range into 10 equal parts and counting the number of observations that fall within each one.</p>
<p>Histograms are helpful because they show the distribution of a single numerical variable. They divide the data into “bins” (ranges of values) and count how many data points fall into each bin. This helps you:</p>
<p>See the shape of the data: You can easily spot if the data is normally distributed, skewed, or has multiple peaks (modes). Identify data spread: Histograms help you understand the spread or range of your data values. Detect outliers: Unusually high or low values become more noticeable in a histogram.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb10-2"><a href="#cb10-2"></a>  <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x=</span>culmen_length_mm),</span>
<span id="cb10-4"><a href="#cb10-4"></a>                 <span class="at">bins=</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="07-data-insights_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Change the bin argument
</div>
</div>
<div class="callout-body-container callout-body">
<p>Change the value specified to the bins argument and observe how the figure changes. It is usually a very good idea to try more than one set of bins in order to have better insights into the data</p>
</div>
</div>
</section><section id="boxplots" class="level3" data-number="4.6.3"><h3 data-number="4.6.3" class="anchored" data-anchor-id="boxplots">
<span class="header-section-number">4.6.3</span> Boxplots</h3>
<p>A <a class="glossary">boxplot<span class="def">A compact visual summary of a datasets distribution, showing the median, interquartile range (IQR), and outliers.</span></a> is a powerful tool for visualizing the distribution of a numerical variable in a compact and easy-to-read format. They provide a wealth of information about the data, including its central tendency, spread, and presence of outliers, while also allowing for comparisons across different groups. Here’s why boxplots are particularly useful:</p>
<ul>
<li><p>Central Tendency: The middle line within the box represents the median value of the data. Unlike the mean, which can be influenced by extreme values, the median provides a robust measure of central tendency, especially for skewed data.</p></li>
<li><p>Spread and Variability: The box itself shows the interquartile range (IQR), which represents the spread of the middle 50% of the data. A wider box means more variability in the data, while a narrower box indicates that the data is more tightly clustered around the median.</p></li>
<li><p>Outliers: Boxplots are particularly useful for identifying <a class="glossary">outliers<span class="def">Data points that are significantly different from the rest of the dataset, often lying far from the median or mean.</span></a> — data points that fall far outside the typical range of values. These are shown as individual points beyond the “whiskers” (the lines extending from the box), making it easy to spot extreme values that could affect your analysis.</p></li>
<li><p>Comparison Between Groups: One of the greatest strengths of boxplots is their ability to compare distributions across different groups. By plotting multiple boxplots side by side (e.g., for different penguin species), you can easily see how a variable’s distribution changes between categories, helping to highlight differences or similarities between groups.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb11-2"><a href="#cb11-2"></a>  <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>culmen_length_mm))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="07-data-insights_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section></section><section id="continuous-and-categorical" class="level2" data-number="4.7"><h2 data-number="4.7" class="anchored" data-anchor-id="continuous-and-categorical">
<span class="header-section-number">4.7</span> Continuous and categorical</h2>
<p>When you have a continuous variable (like culmen length) and want to explore how its distribution varies across a categorical variable (like species), visualizing the data is the best place to start. Simple figures allow us to easily see potential patterns and relationships between the variables.</p>
<p>To investigate how culmen length varies between different penguin species, we can create a simple boxplot that shows the distribution of culmen lengths for each species. This will help us quickly understand whether the different species tend to have different culmen lengths and whether any species has more variability or outliers than others.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>penguins <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> species,</span>
<span id="cb12-3"><a href="#cb12-3"></a>               <span class="at">y =</span> body_mass_g,</span>
<span id="cb12-4"><a href="#cb12-4"></a>               <span class="at">fill =</span> species))<span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5"></a>    <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="fl">0.2</span>)<span class="sc">+</span></span>
<span id="cb12-6"><a href="#cb12-6"></a>  <span class="fu">coord_flip</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="07-data-insights_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>By subgrouping the data, such as looking at the distribution of culmen length by species, we can more easily identify outliers within each group. When we analyze all penguins together, outliers might be harder to spot or might seem more extreme. However, when we break the data down by species, we can see that what might have appeared as an outlier in the overall data may actually be a typical value within a specific group.</p>
<p>This shows us that outliers are context-specific. A value that is unusually large or small for one species might fall well within the normal range for another species. Subgrouping helps us understand that outliers are not absolute—they depend on the context of the data and the groups being compared. This insight is crucial for accurate analysis, as it helps us avoid labeling a data point as unusual without considering its appropriate context.</p>
<section id="density-plots" class="level3" data-number="4.7.1"><h3 data-number="4.7.1" class="anchored" data-anchor-id="density-plots">
<span class="header-section-number">4.7.1</span> Density plots</h3>
<p>Histograms and <a class="glossary">density plots<span class="def"></span></a> are both useful tools for visualizing the distribution of a continuous variable, but they present the information in slightly different ways.</p>
<ul>
<li><p>Histograms divide the data into bins and count how many data points fall into each bin. This gives a blocky visual representation of the data’s distribution and is great for showing the frequency of data points within specific ranges. The choice of bin width can influence how smooth or rough the histogram looks, and it provides an easy way to understand how the data is spread out.</p></li>
<li><p>Density plots, on the other hand, provide a smoothed estimate of the data distribution. Instead of counting data points in bins, a density plot estimates the probability density of the variable, giving a continuous curve that helps visualize the shape of the data. The area under the curve of a density plot sums to 1, making it particularly useful when comparing distributions between groups, as it normalizes the data regardless of sample size.</p></li>
</ul>
<p>In summary, histograms are useful for showing the exact count of data points in specific ranges, while density plots give a smoothed representation of the data’s distribution, helping to highlight the overall shape. Both are valuable tools, and the choice between them depends on the level of detail or smoothness you want to highlight.</p>
<p>Below we have an example of a density plot, more useful when comparing groups of uneven sample sizes:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a>penguins <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">fill =</span> species))<span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x =</span> culmen_length_mm),</span>
<span id="cb13-4"><a href="#cb13-4"></a>                   <span class="at">position =</span> <span class="st">"identity"</span>,</span>
<span id="cb13-5"><a href="#cb13-5"></a>                   <span class="at">alpha =</span> <span class="fl">0.6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="07-data-insights_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section><section id="ggridges" class="level3" data-number="4.7.2"><h3 data-number="4.7.2" class="anchored" data-anchor-id="ggridges">
<span class="header-section-number">4.7.2</span> GGridges</h3>
<p>The package ggridges (Wilke (2021)) provides some excellent extra geoms to supplement ggplot. One if its most useful features is to to allow different groups to be mapped to the y axis, so that histograms are more easily viewed.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="fu">library</span>(ggridges)</span>
<span id="cb14-2"><a href="#cb14-2"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(<span class="at">x =</span> culmen_length_mm, </span>
<span id="cb14-3"><a href="#cb14-3"></a>                     <span class="at">y =</span> species)) <span class="sc">+</span> </span>
<span id="cb14-4"><a href="#cb14-4"></a>  ggridges<span class="sc">::</span><span class="fu">geom_density_ridges</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="07-data-insights_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>When a density plot shows double peaks (also known as bimodal distribution), it often suggests that the data may contain two distinct groups or underlying patterns that are not immediately visible. In such cases, subgrouping the data can help clarify these peaks. By breaking the data down into categories—such as species, gender, or location—we can explore whether the peaks correspond to meaningful subgroups within the dataset.</p>
<p>For example, in the Palmer Penguins dataset, a bimodal distribution of bill length might indicate that different species have distinct bill lengths, each contributing to one of the peaks. Subgrouping by species would allow us to visualize separate distributions for each species and better understand the source of the variation.</p>
<p>Subgrouping helps us gain clarity by revealing if the apparent double peaks are caused by the presence of multiple groups, and it allows us to analyze these groups separately, leading to more accurate insights.</p>
<p>Let’s see what happens when we account for sex:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb15-2"><a href="#cb15-2"></a>  <span class="fu">drop_na</span>() <span class="sc">|&gt;</span> </span>
<span id="cb15-3"><a href="#cb15-3"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> culmen_length_mm, </span>
<span id="cb15-4"><a href="#cb15-4"></a>                     <span class="at">y =</span> species, <span class="at">fill =</span> sex)) <span class="sc">+</span> </span>
<span id="cb15-5"><a href="#cb15-5"></a>    ggridges<span class="sc">::</span><span class="fu">geom_density_ridges</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="07-data-insights_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>If we still see double peaks after subgrouping the data, it suggests that there may be additional underlying factors or patterns within each subgroup that we haven’t accounted for yet. These could be caused by other variables such as age, environmental conditions, or even measurement error, depending on the context of the data.</p>
</section></section><section id="normality" class="level2" data-number="4.8"><h2 data-number="4.8" class="anchored" data-anchor-id="normality">
<span class="header-section-number">4.8</span> Normality</h2>
<p>If our data follows a <a class="glossary">normal distribution<span class="def">Also known as the “Gaussian distribution,” it is a probability distribution that is symmetric about the mean, showing that data near the mean are more frequent in occurrence than data far from the mean.</span></a> , we can use just two key metrics — <strong>mean</strong> and <strong>standard deviation</strong> — to predict how the data is spread out and to calculate the probability of observing a specific value. The normal distribution is symmetric and bell-shaped, meaning most data points cluster around the mean, with fewer observations the farther we move from it.</p>
<section id="why-these-measures-matter" class="level3" data-number="4.8.1"><h3 data-number="4.8.1" class="anchored" data-anchor-id="why-these-measures-matter">
<span class="header-section-number">4.8.1</span> Why These Measures Matter:</h3>
<ul>
<li><p>The <a class="glossary">mean<span class="def">The average of a dataset, calculated by summing all values and dividing by the number of observations.</span></a> gives us a general idea of the “average” value, but the <a class="glossary">standard deviation<span class="def">A measure of the amount of variation or spread in a dataset, indicating how far data points are from the mean on average.</span></a> tells us how reliable that mean is by showing how much the data varies around it.</p></li>
<li><p>Together, these two metrics help us understand the overall distribution of a continuous variable. For normally distributed data, roughly 68% of values lie within one standard deviation of the mean, which provides a good sense of the data’s spread.</p></li>
</ul></section><section id="qqplots" class="level3" data-number="4.8.2"><h3 data-number="4.8.2" class="anchored" data-anchor-id="qqplots">
<span class="header-section-number">4.8.2</span> QQplots</h3>
<p>A QQ plot is a useful tool for visually assessing whether a dataset follows a particular distribution, such as the normal distribution. At first glance, QQ plots may look unfamiliar, but they are simple and powerful once you understand the concept.</p>
<p>In a QQ plot, your sample data is plotted on the y-axis, and the theoretical distribution (often a normal distribution) is plotted on the x-axis. If your data follows a normal distribution, the points in the QQ plot will align along a straight diagonal line. Any deviation from this line indicates that your data departs from the normal distribution, either through skewness, heavy tails, or other irregularities.</p>
<p>How It Works:</p>
<ul>
<li><p>Data Points on the Y-Axis: These are the actual data values from your sample.</p></li>
<li><p>Theoretical Distribution on the X-Axis: These represent what the data would look like if it perfectly followed a normal distribution.</p></li>
</ul>
<p>If the data aligns well with the theoretical distribution, it forms a straight line. If not, the data will curve away from the line, signaling potential departures from normality.</p>
<p>Watch <a href="https://www.youtube.com/watch?v=okjYjClSjOg">this video to see QQ plots explained</a> in action and how they help in assessing the distribution of your data!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="fu">library</span>(qqplotr)</span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(<span class="at">sample =</span> culmen_length_mm))<span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3"></a>    <span class="fu">stat_qq_band</span>() <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4"></a>    <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb16-5"><a href="#cb16-5"></a>    <span class="fu">stat_qq_point</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="07-data-insights_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section><section id="shapiro-test" class="level3" data-number="4.8.3"><h3 data-number="4.8.3" class="anchored" data-anchor-id="shapiro-test">
<span class="header-section-number">4.8.3</span> Shapiro test</h3>
<p>The Shapiro-Wilk test is a commonly used statistical test to check whether a dataset follows a normal distribution. It gives a p-value that helps determine if the data significantly deviates from normality. While useful, the Shapiro test has its limitations, especially when it comes to sample size</p>
<p>Sensitivity to Sample Size: The Shapiro-Wilk test is sensitive to sample size. For large samples, even very small deviations from normality can result in significant p-values, leading to a rejection of normality even when the deviations are minor and practically insignificant.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="fu">library</span>(rstatix)</span>
<span id="cb17-2"><a href="#cb17-2"></a></span>
<span id="cb17-3"><a href="#cb17-3"></a>penguins <span class="sc">%&gt;%</span> </span>
<span id="cb17-4"><a href="#cb17-4"></a>  <span class="fu">shapiro_test</span>(culmen_length_mm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">variable</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left;">culmen_length_mm</td>
<td style="text-align: right;">0.9748548</td>
<td style="text-align: right;">1.12e-05</td>
</tr></tbody>
</table>
</div>
</div>
</div>
<p>Unlike the Shapiro-Wilk test, a QQ plot provides a visual way to check for normality. It allows you to see exactly how the data deviates from a normal distribution. You can spot patterns such as skewness or heavy tails, which the Shapiro test cannot differentiate.</p>
<p>QQ plots are also more flexible with sample size. They work well with both large and small datasets.</p>
</section><section id="normality-in-subgroups" class="level3" data-number="4.8.4"><h3 data-number="4.8.4" class="anchored" data-anchor-id="normality-in-subgroups">
<span class="header-section-number">4.8.4</span> Normality in subgroups</h3>
<p>When you analyze the entire dataset without subgrouping, you combine data from different groups, such as species, locations, or treatments. Each group may have its own unique distribution. For example, in the Palmer Penguins dataset, bill length and bill depth may differ significantly between penguin species. If you test for normality across the entire dataset, the mix of different distributions might lead to misleading results—either falsely showing non-normality or obscuring deviations that are present in specific groups.</p>
<p>Subgrouping allows you to test for normality within each specific group and understand whether the deviations from normality are general or isolated to certain groups.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="fu">library</span>(qqplotr)</span>
<span id="cb18-2"><a href="#cb18-2"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(<span class="at">sample =</span> culmen_length_mm))<span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3"></a>    <span class="fu">stat_qq_band</span>() <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4"></a>    <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5"></a>    <span class="fu">stat_qq_point</span>() <span class="sc">+</span></span>
<span id="cb18-6"><a href="#cb18-6"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="07-data-insights_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a>penguins <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2"></a>  <span class="fu">group_by</span>(species) <span class="sc">|&gt;</span> </span>
<span id="cb19-3"><a href="#cb19-3"></a>  <span class="fu">shapiro_test</span>(culmen_length_mm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: left;">variable</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">culmen_length_mm</td>
<td style="text-align: right;">0.9933618</td>
<td style="text-align: right;">0.7166005</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: left;">culmen_length_mm</td>
<td style="text-align: right;">0.9752496</td>
<td style="text-align: right;">0.1940926</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: left;">culmen_length_mm</td>
<td style="text-align: right;">0.9727224</td>
<td style="text-align: right;">0.0134914</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Now we can see that when splitting into species subgroups - that the qqplots are much better. The Shapiro wilk test indicates that the Gentoo population deviates from a normal distribution for bill length, but our qqplot indicates this is very minor and we can still safely use descriptive statistics of mean and standard deviation that rely on this assumption.</p>
</section></section><section id="summary-statistics" class="level2" data-number="4.9"><h2 data-number="4.9" class="anchored" data-anchor-id="summary-statistics">
<span class="header-section-number">4.9</span> Summary statistics</h2>
<section id="calculating-mean-and-standard-deviation" class="level3" data-number="4.9.1"><h3 data-number="4.9.1" class="anchored" data-anchor-id="calculating-mean-and-standard-deviation">
<span class="header-section-number">4.9.1</span> Calculating mean and standard deviation</h3>
<p>standard deviation (or s) is a measure of how dispersed the data is in relation to the mean. Low standard deviation means data are clustered around the mean, and high standard deviation indicates data are more spread out. We can calculate these easily in R with <code>group_by()</code> and <code>summarise()</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb20-2"><a href="#cb20-2"></a>  <span class="fu">group_by</span>(species) <span class="sc">|&gt;</span> </span>
<span id="cb20-3"><a href="#cb20-3"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(culmen_length_mm),</span>
<span id="cb20-4"><a href="#cb20-4"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(culmen_length_mm))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: right;">48.83382</td>
<td style="text-align: right;">3.339256</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb21-2"><a href="#cb21-2"></a>  <span class="fu">group_by</span>(species) <span class="sc">|&gt;</span> </span>
<span id="cb21-3"><a href="#cb21-3"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(culmen_length_mm, <span class="at">na.rm =</span> T),</span>
<span id="cb21-4"><a href="#cb21-4"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(culmen_length_mm, <span class="at">na.rm =</span>T))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: right;">38.79139</td>
<td style="text-align: right;">2.663405</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: right;">48.83382</td>
<td style="text-align: right;">3.339256</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: right;">47.50488</td>
<td style="text-align: right;">3.081857</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</section><section id="median-and-quartiles" class="level3" data-number="4.9.2"><h3 data-number="4.9.2" class="anchored" data-anchor-id="median-and-quartiles">
<span class="header-section-number">4.9.2</span> Median and quartiles</h3>
<p>If we were dealing with variables that did not fit a normal distribution, using summary statistics like max, min, median, and interquartile range (IQR) provides a robust way to describe the data’s spread and central tendency. Unlike the mean and standard deviation, which are sensitive to outliers and skewed data, the median and IQR give a more accurate representation of the distribution’s center and spread in non-normal data.</p>
<ul>
<li><p>Median: This is the middle value and provides a better measure of central tendency than the mean when data is skewed. IQR (Interquartile Range): This measures the spread of the middle 50% of the data (between the 25th and 75th percentiles) and is less affected by extreme values.</p></li>
<li><p>Min and Max: These values show the range of the data, highlighting any extreme values or outliers.</p></li>
</ul>
<p>These summary statistics directly correspond to the boxplot: the median is the line inside the box, the IQR defines the box’s edges, and the min/max (after removing outliers) are represented by the ends of the whiskers.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb22-2"><a href="#cb22-2"></a>  <span class="fu">group_by</span>(species) <span class="sc">|&gt;</span> </span>
<span id="cb22-3"><a href="#cb22-3"></a>  <span class="fu">summarise</span>(<span class="at">median =</span> <span class="fu">median</span>(culmen_length_mm, <span class="at">na.rm =</span> T),</span>
<span id="cb22-4"><a href="#cb22-4"></a>            <span class="at">quantile =</span> <span class="fu">quantile</span>(culmen_length_mm, <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>), <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb22-5"><a href="#cb22-5"></a>            <span class="at">max =</span> <span class="fu">max</span>(culmen_length_mm, <span class="at">na.rm =</span> T),</span>
<span id="cb22-6"><a href="#cb22-6"></a>            <span class="at">min =</span> <span class="fu">min</span>(culmen_length_mm, <span class="at">na.rm =</span> T)</span>
<span id="cb22-7"><a href="#cb22-7"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">quantile</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">min</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: right;">38.80</td>
<td style="text-align: right;">36.750</td>
<td style="text-align: right;">46.0</td>
<td style="text-align: right;">32.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adelie</td>
<td style="text-align: right;">38.80</td>
<td style="text-align: right;">38.800</td>
<td style="text-align: right;">46.0</td>
<td style="text-align: right;">32.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: right;">38.80</td>
<td style="text-align: right;">40.750</td>
<td style="text-align: right;">46.0</td>
<td style="text-align: right;">32.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: right;">49.55</td>
<td style="text-align: right;">46.350</td>
<td style="text-align: right;">58.0</td>
<td style="text-align: right;">40.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: right;">49.55</td>
<td style="text-align: right;">49.550</td>
<td style="text-align: right;">58.0</td>
<td style="text-align: right;">40.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: right;">49.55</td>
<td style="text-align: right;">51.075</td>
<td style="text-align: right;">58.0</td>
<td style="text-align: right;">40.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: right;">47.30</td>
<td style="text-align: right;">45.300</td>
<td style="text-align: right;">59.6</td>
<td style="text-align: right;">40.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: right;">47.30</td>
<td style="text-align: right;">47.300</td>
<td style="text-align: right;">59.6</td>
<td style="text-align: right;">40.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: right;">47.30</td>
<td style="text-align: right;">49.550</td>
<td style="text-align: right;">59.6</td>
<td style="text-align: right;">40.9</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you ran the command above you likely received a warning in your R console</p>
<pre><code>Warning: Returning more (or less) than 1 row per `summarise()` group was deprecated in
dplyr 1.1.0.
ℹ Please use `reframe()` instead.</code></pre>
<p>This is because <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> is supposed to only supply one row per group - by asking for the different quartiles from each group it forces it to print more rows. Try doing what R asks and see what happens</p>
<p><a href="https://dplyr.tidyverse.org/reference/reframe.html">See here</a></p>
</div>
</div>
</section></section><section id="collinearity" class="level2" data-number="4.10"><h2 data-number="4.10" class="anchored" data-anchor-id="collinearity">
<span class="header-section-number">4.10</span> Collinearity</h2>
<p>Collinearity occurs when two or more independent variables in a dataset are highly correlated with each other, meaning that they show a strong linear relationship. In simpler terms, it means that one variable can be almost perfectly predicted by another. Collinearity is particularly problematic in regression analysis, where you want each independent variable to provide unique information about the outcome (dependent variable).</p>
<p>Imagine you’re studying penguin bill characteristics in the Palmer Penguins dataset. If you include both culmen length and flipper length are highly correlated, then collinearity may occur. This would make it difficult to determine whether changes in culmen depth are due to culmen length or flipper length, or a combination of both, as they provide overlapping information.</p>
<section id="ggally" class="level3" data-number="4.10.1"><h3 data-number="4.10.1" class="anchored" data-anchor-id="ggally">
<span class="header-section-number">4.10.1</span> GGally</h3>
<p>The R package <code>GGally</code> helps us understand the relationships between variables, by producing a pairwise matric grid made of:</p>
<ul>
<li><p>Scatterplots: The scatterplots in a pairwise matrix (created by ggpairs()) allow you to visually inspect the relationship between pairs of continuous variables. If two variables show a strong linear relationship (points forming a clear diagonal line), it suggests collinearity between those variables.</p></li>
<li><p>Correlation Coefficients: In the pairwise matrix, you can also display correlation coefficients. When these values are close to 1 (positive correlation) or -1 (negative correlation), it suggests that the variables are highly correlated and might indicate collinearity.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb24-2"><a href="#cb24-2"></a></span>
<span id="cb24-3"><a href="#cb24-3"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb24-4"><a href="#cb24-4"></a>  <span class="fu">select</span>(species, </span>
<span id="cb24-5"><a href="#cb24-5"></a>         island, </span>
<span id="cb24-6"><a href="#cb24-6"></a>         culmen_length_mm, </span>
<span id="cb24-7"><a href="#cb24-7"></a>         culmen_depth_mm, </span>
<span id="cb24-8"><a href="#cb24-8"></a>         flipper_length_mm, </span>
<span id="cb24-9"><a href="#cb24-9"></a>         body_mass_g, </span>
<span id="cb24-10"><a href="#cb24-10"></a>         sex) <span class="sc">|&gt;</span> </span>
<span id="cb24-11"><a href="#cb24-11"></a>  <span class="fu">ggpairs</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="07-data-insights_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>From these pairwise plots we can see that there <em>is</em> a correlation between flipper length, body mass and the culmen length and depth variables. This is useful information to know when considering the relationship between variables for cause and effect, and will be important when build statistical models.</p>
<section id="applying-subgroups-of-color-in-ggally-using-ggplot2" class="level4" data-number="4.10.1.1"><h4 data-number="4.10.1.1" class="anchored" data-anchor-id="applying-subgroups-of-color-in-ggally-using-ggplot2">
<span class="header-section-number">4.10.1.1</span> Applying Subgroups of Color in GGally (Using ggplot2)</h4>
<p>Since GGally builds on ggplot2, you can apply the same customisations that ggplot2 allows, including the use of color to represent different subgroups in your data. This is especially useful when exploring relationships between variables, as it helps highlight patterns or differences between categories (e.g., species, sex, or location).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb25-2"><a href="#cb25-2"></a>  <span class="fu">ggpairs</span>(<span class="at">columns =</span> <span class="fu">c</span>(</span>
<span id="cb25-3"><a href="#cb25-3"></a>         <span class="st">"island"</span>, </span>
<span id="cb25-4"><a href="#cb25-4"></a>         <span class="st">"culmen_length_mm"</span>, </span>
<span id="cb25-5"><a href="#cb25-5"></a>         <span class="st">"culmen_depth_mm"</span>, </span>
<span id="cb25-6"><a href="#cb25-6"></a>         <span class="st">"flipper_length_mm"</span>, </span>
<span id="cb25-7"><a href="#cb25-7"></a>         <span class="st">"body_mass_g"</span>, </span>
<span id="cb25-8"><a href="#cb25-8"></a>         <span class="st">"sex"</span>), </span>
<span id="cb25-9"><a href="#cb25-9"></a>         ggplot2<span class="sc">::</span><span class="fu">aes</span>(<span class="at">colour =</span> species))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="07-data-insights_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Why is this useful? It means we can identify group-specific trends: Adding colour based on a categorical variable (like species) helps you quickly spot trends or patterns that may exist only within certain groups.</p>
</section></section></section><section id="correlation" class="level2" data-number="4.11"><h2 data-number="4.11" class="anchored" data-anchor-id="correlation">
<span class="header-section-number">4.11</span> Correlation</h2>
<p>A common measure of association between two numerical variables is the correlation coefficient. The correlation metric is a numerical measure of the strength of an association</p>
<p>There are several measures of correlation including:</p>
<ul>
<li><p>Pearson’s correlation coefficient : good for describing linear associations</p></li>
<li><p>Spearman’s rank correlation coefficient: a rank ordered correlation - good for when the assumptions for Pearson’s correlation is not met.</p></li>
</ul>
<p>Pearson’s correlation coefficient <code>r</code> is designed to measure the strength of a linear (straight line) association. Pearson’s takes a value between -1 and 1.</p>
<ul>
<li><p>A value of 0 means there is no linear association between the variables</p></li>
<li><p>A value of 1 means there is a perfect positive association between the variables</p></li>
<li><p>A value of -1 means there is a perfect negative association between the variables</p></li>
</ul>
<p>A perfect association is one where we can predict the value of one variable with complete accuracy, just by knowing the value of the other variable.</p>
<p>We can use the <code><a href="https://rpkgs.datanovia.com/rstatix/reference/cor_test.html">rstatix::cor_test()</a></code> function in R to calculate Pearson’s correlation coefficient.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="fu">library</span>(rstatix)</span>
<span id="cb26-2"><a href="#cb26-2"></a></span>
<span id="cb26-3"><a href="#cb26-3"></a>penguins <span class="sc">%&gt;%</span> </span>
<span id="cb26-4"><a href="#cb26-4"></a>  <span class="fu">cor_test</span>(culmen_length_mm, </span>
<span id="cb26-5"><a href="#cb26-5"></a>           culmen_depth_mm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 18%">
<col style="width: 6%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 9%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">var1</th>
<th style="text-align: left;">var2</th>
<th style="text-align: right;">cor</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
<th style="text-align: left;">method</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left;">culmen_length_mm</td>
<td style="text-align: left;">culmen_depth_mm</td>
<td style="text-align: right;">-0.24</td>
<td style="text-align: right;">-4.459093</td>
<td style="text-align: right;">1.12e-05</td>
<td style="text-align: right;">-0.3328072</td>
<td style="text-align: right;">-0.1323004</td>
<td style="text-align: left;">Pearson</td>
</tr></tbody>
</table>
</div>
</div>
</div>
<p>This tells us two features of the association. It’s sign and magnitude. The coefficient is negative, so as bill length increases, bill depth decreases. The value -0.24 indicates a weak negative relationship.</p>
<p>Because Pearson’s coefficient is designed to summarise the strength of a linear relationship, this can be misleading if the relationship is not linear e.g.&nbsp;curved or humped. This is why it’s always a good idea to plot the relationship first (see above).</p>
<p>Even when the relationship is linear, it doesn’t tell us anything about the steepness of the association (see above). It only tells us how often a change in one variable can predict the change in the other not the value of that change.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/correlation_examples.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%" alt="Correlation examples"></p>
</figure>
</div>
</div>
</div>
<p>This can be difficult to understand at first, so carefully consider the figure above.</p>
<ul>
<li><p>The first row above shows differing levels of the strength of association. If we drew a perfect straight line between two variables, how closely do the data points fit around this line.</p></li>
<li><p>The second row shows a series of perfect linear relationships. We can accurately predict the value of one variable just by knowing the value of the other variable, but the steepness of the relationship in each example is very different. This is important because it means a perfect association can still have a small effect.</p></li>
<li><p>The third row shows a series of associations where there is clearly a relationship between the two variables, but it is also not linear so would be inappropriate for a Pearson’s correlation.</p></li>
</ul>
<section id="assumptions-of-pearsons-correlation" class="level3" data-number="4.11.1"><h3 data-number="4.11.1" class="anchored" data-anchor-id="assumptions-of-pearsons-correlation">
<span class="header-section-number">4.11.1</span> Assumptions of Pearson’s correlation</h3>
<ul>
<li><p>A linear relationship</p></li>
<li><p>Normal distribution of the variance</p></li>
</ul>
<p>In our case we have already looked at the relationship and the assumptions of normality and would conclude our data is basically fine for using Pearson’s correlation.</p>
<p>But what should we do if the relationship between our variables is non-linear or does not follow a normal distribution? Instead of using Pearson’s correlation coefficient we can calculate something called a rank correlation.</p>
</section><section id="spearmans-rank-correlation" class="level3" data-number="4.11.2"><h3 data-number="4.11.2" class="anchored" data-anchor-id="spearmans-rank-correlation">
<span class="header-section-number">4.11.2</span> Spearman’s rank correlation</h3>
<p>Instead of working with the raw values of our two variables we can use rank ordering instead. The idea is pretty simple if we start with the lowest vaule in a variable and order it as ‘1’, then assign labels ‘2’, ‘3’ etc. as we ascend in rank order. We can see a way that this could be applied manually with the function dense_rank from dplyr below:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a><span class="fu">library</span>(rstatix)</span>
<span id="cb27-2"><a href="#cb27-2"></a></span>
<span id="cb27-3"><a href="#cb27-3"></a>penguins <span class="sc">%&gt;%</span> </span>
<span id="cb27-4"><a href="#cb27-4"></a>  <span class="fu">cor_test</span>(culmen_length_mm, </span>
<span id="cb27-5"><a href="#cb27-5"></a>           culmen_depth_mm,</span>
<span id="cb27-6"><a href="#cb27-6"></a>           <span class="at">method =</span> <span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 23%">
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">var1</th>
<th style="text-align: left;">var2</th>
<th style="text-align: right;">cor</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p</th>
<th style="text-align: left;">method</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left;">culmen_length_mm</td>
<td style="text-align: left;">culmen_depth_mm</td>
<td style="text-align: right;">-0.22</td>
<td style="text-align: right;">8145268</td>
<td style="text-align: right;">3.51e-05</td>
<td style="text-align: left;">Spearman</td>
</tr></tbody>
</table>
</div>
</div>
</div>
<p>You can see that we get a similar <em>but not identical</em> estimate of the strength of association. Generally non-parametric tests are less powerful, but have fewer assumptions about the structure of our data.</p>
</section><section id="graphical-summaries-between-numeric-variables" class="level3" data-number="4.11.3"><h3 data-number="4.11.3" class="anchored" data-anchor-id="graphical-summaries-between-numeric-variables">
<span class="header-section-number">4.11.3</span> Graphical summaries between numeric variables</h3>
<p>Correlation coefficients are a quick and simple way to attach a metric to the level of association between two variables. They are limited however in that a single number can never capture the every aspect of their relationship. This is why we visualise our data, and the best way to do that for two continuous variables is to make a scatterplot</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a>scatterplot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(<span class="at">x=</span> culmen_length_mm, </span>
<span id="cb28-2"><a href="#cb28-2"></a>                                    <span class="at">y=</span> culmen_depth_mm)) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3"></a>  <span class="fu">geom_point</span>()</span>
<span id="cb28-4"><a href="#cb28-4"></a></span>
<span id="cb28-5"><a href="#cb28-5"></a>scatterplot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="07-data-insights_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<section id="marginal-plots" class="level4" data-number="4.11.3.1"><h4 data-number="4.11.3.1" class="anchored" data-anchor-id="marginal-plots">
<span class="header-section-number">4.11.3.1</span> Marginal plots</h4>
<p>Marginal plots are useful when you want to explore the distribution of individual variables alongside a scatterplot of the relationship between two variables. They add histograms, density plots, or boxplots to the margins of a scatterplot, providing extra information about the distribution of each variable separately. So we would could add any of the plots we used previously to look at variance in each of our variables <code>culmen_length_mm</code> and <code>culmen_depth_mm</code></p>
</section><section id="how-to-create-marginal-plots-using-patchwork-in-r" class="level4" data-number="4.11.3.2"><h4 data-number="4.11.3.2" class="anchored" data-anchor-id="how-to-create-marginal-plots-using-patchwork-in-r">
<span class="header-section-number">4.11.3.2</span> How to Create Marginal Plots: Using patchwork in R</h4>
<p><code>patchwork</code> is an R package that makes it easy to combine multiple ggplots into a single plot layout, including creating layouts for marginal plots. While ggplot2 doesn’t natively support marginal plots, patchwork allows you to combine the scatterplot with additional histograms or density plots at the top and side, creating a custom marginal plot.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="fu">library</span>(patchwork) <span class="co"># package calls should be placed at the TOP of your script</span></span>
<span id="cb29-2"><a href="#cb29-2"></a></span>
<span id="cb29-3"><a href="#cb29-3"></a>bill_depth_marginal <span class="ot">&lt;-</span> penguins <span class="sc">%&gt;%</span> </span>
<span id="cb29-4"><a href="#cb29-4"></a>  <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x=</span>culmen_depth_mm), <span class="at">fill=</span><span class="st">"darkgrey"</span>)<span class="sc">+</span></span>
<span id="cb29-6"><a href="#cb29-6"></a>  <span class="fu">theme_void</span>()<span class="sc">+</span></span>
<span id="cb29-7"><a href="#cb29-7"></a>  <span class="fu">coord_flip</span>() <span class="co"># this graph needs to be rotated</span></span>
<span id="cb29-8"><a href="#cb29-8"></a></span>
<span id="cb29-9"><a href="#cb29-9"></a>bill_length_marginal <span class="ot">&lt;-</span> penguins <span class="sc">%&gt;%</span> </span>
<span id="cb29-10"><a href="#cb29-10"></a>  <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb29-11"><a href="#cb29-11"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x=</span>culmen_length_mm), <span class="at">fill=</span><span class="st">"darkgrey"</span>)<span class="sc">+</span></span>
<span id="cb29-12"><a href="#cb29-12"></a>  <span class="fu">theme_void</span>()</span>
<span id="cb29-13"><a href="#cb29-13"></a></span>
<span id="cb29-14"><a href="#cb29-14"></a>layout <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb29-15"><a href="#cb29-15"></a><span class="st">AA#</span></span>
<span id="cb29-16"><a href="#cb29-16"></a><span class="st">BBC</span></span>
<span id="cb29-17"><a href="#cb29-17"></a><span class="st">BBC"</span></span>
<span id="cb29-18"><a href="#cb29-18"></a></span>
<span id="cb29-19"><a href="#cb29-19"></a><span class="co"># layout is easiest to organise using a text distribution, where ABC equal the three plots in order, and the grid is how much space they take up. We could easily make the main plot bigger and marginals smaller with</span></span>
<span id="cb29-20"><a href="#cb29-20"></a></span>
<span id="cb29-21"><a href="#cb29-21"></a>scatterplot <span class="ot">&lt;-</span> scatterplot <span class="sc">+</span></span>
<span id="cb29-22"><a href="#cb29-22"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>,</span>
<span id="cb29-23"><a href="#cb29-23"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>)</span>
<span id="cb29-24"><a href="#cb29-24"></a></span>
<span id="cb29-25"><a href="#cb29-25"></a>bill_length_marginal<span class="sc">+</span></span>
<span id="cb29-26"><a href="#cb29-26"></a>  scatterplot<span class="sc">+</span></span>
<span id="cb29-27"><a href="#cb29-27"></a>  bill_depth_marginal<span class="sc">+</span> </span>
<span id="cb29-28"><a href="#cb29-28"></a>  <span class="co"># order of plots is important</span></span>
<span id="cb29-29"><a href="#cb29-29"></a>  <span class="fu">plot_layout</span>(<span class="at">design=</span>layout) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="07-data-insights_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="co"># uses the layout argument defined above to arrange the size and position of plots</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>From this plot we would conclude that there is weak <select class="webex-select"><option value="blank"></option>
<option value="">positive</option>
<option value="answer">negative</option></select> relationship between culmen length and culmen depth.</p>
</section></section></section><section id="important-variables" class="level2" data-number="4.12"><h2 data-number="4.12" class="anchored" data-anchor-id="important-variables">
<span class="header-section-number">4.12</span> Important variables</h2>
<p>When analyzing the correlation between two variables, it’s essential to consider important categories or grouping variables (like species, gender, location, or time) to avoid misleading results and oversimplified interpretations. Ignoring relevant categories can result in omitted variable bias, which occurs when a key variable is left out of the analysis and its influence distorts the observed relationship between the variables of interest.</p>
<p>Think about important categories or subgroups that should be included when considering the relationship between culment length and depth?</p>
<div class="webex-solution">
<button>
Solution
</button>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a>colours <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"cyan"</span>,</span>
<span id="cb31-2"><a href="#cb31-2"></a>             <span class="st">"darkorange"</span>,</span>
<span id="cb31-3"><a href="#cb31-3"></a>             <span class="st">"purple"</span>)</span>
<span id="cb31-4"><a href="#cb31-4"></a></span>
<span id="cb31-5"><a href="#cb31-5"></a>scatterplot_2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(<span class="at">x=</span> culmen_length_mm, </span>
<span id="cb31-6"><a href="#cb31-6"></a>                     <span class="at">y=</span> culmen_depth_mm,</span>
<span id="cb31-7"><a href="#cb31-7"></a>                     <span class="at">colour=</span>species)) <span class="sc">+</span></span>
<span id="cb31-8"><a href="#cb31-8"></a>    <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb31-9"><a href="#cb31-9"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>,</span>
<span id="cb31-10"><a href="#cb31-10"></a>              <span class="at">se=</span><span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb31-11"><a href="#cb31-11"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values=</span>colours)<span class="sc">+</span></span>
<span id="cb31-12"><a href="#cb31-12"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb31-13"><a href="#cb31-13"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"none"</span>)<span class="sc">+</span></span>
<span id="cb31-14"><a href="#cb31-14"></a>    <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Bill length (mm)"</span>,</span>
<span id="cb31-15"><a href="#cb31-15"></a>         <span class="at">y=</span><span class="st">"Bill depth (mm)"</span>)</span>
<span id="cb31-16"><a href="#cb31-16"></a></span>
<span id="cb31-17"><a href="#cb31-17"></a>bill_depth_marginal_2 <span class="ot">&lt;-</span> penguins <span class="sc">%&gt;%</span> </span>
<span id="cb31-18"><a href="#cb31-18"></a>  <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb31-19"><a href="#cb31-19"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x=</span>culmen_depth_mm,</span>
<span id="cb31-20"><a href="#cb31-20"></a>                   <span class="at">fill=</span>species),</span>
<span id="cb31-21"><a href="#cb31-21"></a>               <span class="at">alpha=</span><span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb31-22"><a href="#cb31-22"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span>colours)<span class="sc">+</span></span>
<span id="cb31-23"><a href="#cb31-23"></a>  <span class="fu">theme_void</span>()<span class="sc">+</span></span>
<span id="cb31-24"><a href="#cb31-24"></a>  <span class="fu">coord_flip</span>() <span class="co"># this graph needs to be rotated</span></span>
<span id="cb31-25"><a href="#cb31-25"></a></span>
<span id="cb31-26"><a href="#cb31-26"></a>bill_length_marginal_2 <span class="ot">&lt;-</span> penguins <span class="sc">%&gt;%</span> </span>
<span id="cb31-27"><a href="#cb31-27"></a>  <span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb31-28"><a href="#cb31-28"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x=</span>culmen_length_mm,</span>
<span id="cb31-29"><a href="#cb31-29"></a>                   <span class="at">fill=</span>species),</span>
<span id="cb31-30"><a href="#cb31-30"></a>               <span class="at">alpha=</span><span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb31-31"><a href="#cb31-31"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span>colours)<span class="sc">+</span></span>
<span id="cb31-32"><a href="#cb31-32"></a>  <span class="fu">theme_void</span>()<span class="sc">+</span></span>
<span id="cb31-33"><a href="#cb31-33"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"none"</span>)</span>
<span id="cb31-34"><a href="#cb31-34"></a></span>
<span id="cb31-35"><a href="#cb31-35"></a>layout2 <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb31-36"><a href="#cb31-36"></a><span class="st">AAA#</span></span>
<span id="cb31-37"><a href="#cb31-37"></a><span class="st">BBBC</span></span>
<span id="cb31-38"><a href="#cb31-38"></a><span class="st">BBBC</span></span>
<span id="cb31-39"><a href="#cb31-39"></a><span class="st">BBBC"</span></span>
<span id="cb31-40"><a href="#cb31-40"></a></span>
<span id="cb31-41"><a href="#cb31-41"></a>bill_length_marginal_2<span class="sc">+</span>scatterplot_2<span class="sc">+</span>bill_depth_marginal_2<span class="sc">+</span> <span class="co"># order of plots is important</span></span>
<span id="cb31-42"><a href="#cb31-42"></a>  <span class="fu">plot_layout</span>(<span class="at">design=</span>layout2) <span class="co"># uses the layout argument defined above to arrange the size and position of plots</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="07-data-insights_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>We now clearly see a striking <strong>reversal</strong> of our previous trend, that in fact within each species of penguin there is an overall positive association between bill length and depth.</p>
<p>This is called <strong>Simpson’s Paradox</strong> it is a classic example of omitted variable bias, where a trend observed in different groups reverses or disappears when the data is combined. This happens when a key variable (often categorical) is not included in the analysis, leading to misleading conclusions.</p>
<p>This should prompt us to re-evaluate our correlation metrics:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a>penguins <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="#cb32-2"></a>  <span class="fu">group_by</span>(species) <span class="sc">%&gt;%</span> </span>
<span id="cb32-3"><a href="#cb32-3"></a>  <span class="fu">cor_test</span>(culmen_length_mm, </span>
<span id="cb32-4"><a href="#cb32-4"></a>           culmen_depth_mm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 10%">
<col style="width: 18%">
<col style="width: 17%">
<col style="width: 5%">
<col style="width: 10%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 8%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: left;">var1</th>
<th style="text-align: left;">var2</th>
<th style="text-align: right;">cor</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
<th style="text-align: left;">method</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">culmen_length_mm</td>
<td style="text-align: left;">culmen_depth_mm</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">5.193285</td>
<td style="text-align: right;">7e-07</td>
<td style="text-align: right;">0.2472226</td>
<td style="text-align: right;">0.5187796</td>
<td style="text-align: left;">Pearson</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: left;">culmen_length_mm</td>
<td style="text-align: left;">culmen_depth_mm</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: right;">7.014647</td>
<td style="text-align: right;">0e+00</td>
<td style="text-align: right;">0.4917326</td>
<td style="text-align: right;">0.7717134</td>
<td style="text-align: left;">Pearson</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: left;">culmen_length_mm</td>
<td style="text-align: left;">culmen_depth_mm</td>
<td style="text-align: right;">0.64</td>
<td style="text-align: right;">9.244703</td>
<td style="text-align: right;">0e+00</td>
<td style="text-align: right;">0.5262952</td>
<td style="text-align: right;">0.7365271</td>
<td style="text-align: left;">Pearson</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>We now see that all of our correlation coefficients are stronger and positive <em>within</em> each species.</p>
</div>
</section><section id="summary" class="level2" data-number="4.13"><h2 data-number="4.13" class="anchored" data-anchor-id="summary">
<span class="header-section-number">4.13</span> Summary</h2>
<p>When analysing data, it’s important to start with simple visualizations like scatterplots, boxplots, or histograms to uncover basic patterns and distributions. Before continuing with simple visualisations of relationships and groupings. These tools help provide quick insights into your data, such as distribution, trends, or outliers.</p>
<p>However, it’s equally important to think carefully about the context of your data. This includes considering grouping variables (like species, sex, or location) to avoid pitfalls like omitted variable bias or Simpson’s Paradox, where important patterns may be hidden or misrepresented if key variables are ignored.</p>
<p>By incorporating relevant categories and ensuring you’re accounting for potential confounding variables, you make sure your analysis is more accurate, insightful, and meaningful. Always take a moment to reflect on the broader context before drawing conclusions from simple data summaries</p>
</section><section id="glossary" class="level2" data-number="4.14"><h2 data-number="4.14" class="anchored" data-anchor-id="glossary">
<span class="header-section-number">4.14</span> Glossary</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">definition</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">bias</td>
<td style="text-align: left;">A systematic error or distortion in data collection or analysis that leads to inaccurate conclusions or results.</td>
</tr>
<tr class="even">
<td style="text-align: left;">boxplot</td>
<td style="text-align: left;">A compact visual summary of a datasets distribution, showing the median, interquartile range (IQR), and outliers.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">central tendency</td>
<td style="text-align: left;">A statistical measure that identifies the center or typical value in a dataset, often represented by the mean, median, or mode.</td>
</tr>
<tr class="even">
<td style="text-align: left;">confounding variable</td>
<td style="text-align: left;">A variable that affects both the independent and dependent variables, potentially distorting the observed relationship between them.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">correlation coefficient</td>
<td style="text-align: left;">A numerical value ranging from -1 to 1 that measures the strength and direction of the linear relationship between two variables.</td>
</tr>
<tr class="even">
<td style="text-align: left;">density plots</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">histogram</td>
<td style="text-align: left;">A graphical representation of the distribution of a dataset by grouping data into bins and showing the frequency of observations within each bin.</td>
</tr>
<tr class="even">
<td style="text-align: left;">mean</td>
<td style="text-align: left;">The average of a dataset, calculated by summing all values and dividing by the number of observations.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">normal distribution</td>
<td style="text-align: left;">Also known as the "Gaussian distribution," it is a probability distribution that is symmetric about the mean, showing that data near the mean are more frequent in occurrence than data far from the mean.</td>
</tr>
<tr class="even">
<td style="text-align: left;">outliers</td>
<td style="text-align: left;">Data points that are significantly different from the rest of the dataset, often lying far from the median or mean.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">scatterplots</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">standard deviation</td>
<td style="text-align: left;">A measure of the amount of variation or spread in a dataset, indicating how far data points are from the mean on average.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">variation</td>
<td style="text-align: left;">A measure of how spread out or dispersed the data points are in relation to each other or the central value.</td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section id="reading" class="level2" data-number="4.15"><h2 data-number="4.15" class="anchored" data-anchor-id="reading">
<span class="header-section-number">4.15</span> Reading</h2>
<ul>
<li><a href="https://doi.org/10.1111/j.2041-210X.2009.00001.x">A protocol for data exploration to avoid common statistical problems</a></li>
</ul>


</section></main><!-- /main --><script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script><script>
// open rdrr links externally ----

var exlinks = document.querySelectorAll("a[href^='https://rdrr.io']");
var exlink_func = function(){
  window.open(this.href);
  return false;
};
for (var i = 0; i < exlinks.length; i++) {
    exlinks[i].addEventListener('click', exlink_func, false);
}

// visible second sidebar in mobile ----

function move_sidebar() {
  var toc = document.getElementById("TOC");
  var small_sidebar = document.querySelector("#quarto-sidebar .sidebar-menu-container");
  var right_sidebar = document.getElementById("quarto-margin-sidebar");

  if (window.innerWidth < 768) {
    small_sidebar.append(toc);
  } else {
    right_sidebar.append(toc);
  }
}
move_sidebar();
window.onresize = move_sidebar;
</script><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./06-data-bias.html" class="pagination-link" aria-label="Data bias">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data bias</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./r-basics.html" class="pagination-link" aria-label="R Basics">
        <span class="nav-page-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">R Basics</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>CC-BY (2024) Philip Leftwich</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>