{
  "hash": "8b9217d0a506c27b5eaaecfd44294578",
  "result": {
    "engine": "knitr",
    "markdown": "# Linear models in R {.unnumbered}\n\n\n\n\n\nIn hour 1 you ranked scenarios by strength of evidence and arrived at\nthe t-statistic as the ratio of estimate to standard error. Here you\nfit the linear model in R and read its coefficient table.\n\nThe data are the same paired differences you have worked with since\nSession 2: the height of the cross-pollinated plant minus the height\nof the self-pollinated plant within each pot.\n\n## The paired differences {#sec-data}\n\n:::{.task}\n::::{.task-header}\n**Task: inspect the paired differences**\n::::\n\n::::{.task-container}\n\nRun the code below to see the fifteen paired differences. These are\nthe same values you used in Sessions 2 and 3.\n\n::::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndarwin_diff |>\n  select(pair, Cross, Self, difference)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| pair|  Cross|   Self| difference|\n|----:|------:|------:|----------:|\n|    1| 23.500| 17.375|      6.125|\n|    2| 12.000| 20.375|     -8.375|\n|    3| 21.000| 20.000|      1.000|\n|    4| 22.000| 20.000|      2.000|\n|    5| 19.125| 18.375|      0.750|\n|    6| 21.500| 18.625|      2.875|\n|    7| 22.125| 18.625|      3.500|\n|    8| 20.375| 15.250|      5.125|\n|    9| 18.250| 16.500|      1.750|\n|   10| 21.625| 18.000|      3.625|\n|   11| 23.250| 16.250|      7.000|\n|   12| 21.000| 18.000|      3.000|\n|   13| 22.125| 12.750|      9.375|\n|   14| 23.000| 15.500|      7.500|\n|   15| 12.000| 18.000|     -6.000|\n\n</div>\n:::\n:::\n\n\n## Fit the intercept-only model {#sec-fit}\n\n:::{.task}\n::::{.task-header}\n**Task: predict the intercept**\n::::\n\n::::{.task-container}\n\nBefore running any code, write down your prediction. You have computed\nthe mean of these differences before. What value do you expect the\nintercept to be?\n\n::::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlsmodel1 <- lm(difference ~ 1, data = darwin_diff)\n```\n:::\n\n\nThe formula `difference ~ 1` means \"fit an intercept only.\" The\nintercept is the mean of the paired differences. The coefficient\ntable tests whether that mean differs from zero — the same question\nthe permutation test in Session 3 answered.\n\n## Read the coefficient table {#sec-summary}\n\n:::{.task}\n::::{.task-header}\n**Task: read the summary output**\n::::\n\n::::{.task-container}\n\nRun the code below. Compare the intercept with your prediction, then\nanswer:\n\n1. What does the estimate represent?\n2. What does the t-value represent, and how does it relate to the\n   ranking exercise from hour 1?\n3. Is there evidence that the mean difference is not zero?\n\n\n<div class='webex-solution'><button>Answer</button>\n\n1. The estimate is the mean of the fifteen paired differences — the\n   average advantage of cross-pollination over self-pollination\n   within a pot.\n2. The t-value is the estimate divided by its standard error. A\n   larger absolute t-value means the estimate is further from zero\n   in standard-error units, just as in the ranking exercise.\n3. Check the p-value. If it is below 0.05, there is evidence that\n   the mean difference is not zero, consistent with the permutation\n   test from Session 3.\n\n</div>\n\n\n::::\n:::\n\n::: {.panel-tabset}\n\n## Base R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lsmodel1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = difference ~ 1, data = darwin_diff)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.9917  -1.2417   0.3833   3.0083   6.7583 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)  \n(Intercept)    2.617      1.218   2.148   0.0497 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.718 on 14 degrees of freedom\n```\n\n\n:::\n:::\n\n\n## Broom\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbroom::tidy(lsmodel1, conf.int = TRUE)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        | estimate| std.error| statistic|   p.value|  conf.low| conf.high|\n|:-----------|--------:|---------:|---------:|---------:|---------:|---------:|\n|(Intercept) | 2.616667|  1.218195|  2.147988| 0.0497029| 0.0038992|  5.229434|\n\n</div>\n:::\n:::\n\n\n:::\n\n## Confidence interval from the model {#sec-ci}\n\n:::{.task}\n::::{.task-header}\n**Task: obtain and interpret the confidence interval**\n::::\n\n::::{.task-container}\n\nRun the code below. The output is a 95% confidence interval for the\nmean paired difference.\n\n1. Does this interval include zero?\n2. Compare it with the confidence interval you computed in Session 2.\n   Are the values the same (or very close)?\n\n\n<div class='webex-solution'><button>Answer</button>\n\n1. If the interval does not include zero, this is consistent with the\n   p-value being below 0.05.\n2. The values should match or be very close. The linear model and the\n   manual computation from Session 2 use the same formula: estimate\n   ± critical value × SE.\n\n</div>\n\n\n::::\n:::\n\n::: {.panel-tabset}\n\n## Base R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(lsmodel1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  2.5 %   97.5 %\n(Intercept) 0.003899165 5.229434\n```\n\n\n:::\n:::\n\n\n## Broom\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbroom::tidy(lsmodel1, conf.int = TRUE)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        | estimate| std.error| statistic|   p.value|  conf.low| conf.high|\n|:-----------|--------:|---------:|---------:|---------:|---------:|---------:|\n|(Intercept) | 2.616667|  1.218195|  2.147988| 0.0497029| 0.0038992|  5.229434|\n\n</div>\n:::\n:::\n\n\n:::\n\n::: {.callout-note}\n## A simple write-up\nFrom the linear model on paired differences: \"Cross-pollinated maize\nplants were taller on average than self-pollinated plants, with a\nmean paired difference of 2.62 inches (95% CI: 0.004, 5.22;\nt(14) = 2.15, p = 0.05).\"\n\nNote: the degrees of freedom are 14 (fifteen pairs minus one), not\n28. Match the values to your output.\n:::\n\n## Compare with the one-sample t-test {#sec-compare-ttest}\n\n:::{.task}\n::::{.task-header}\n**Task: confirm the equivalence**\n::::\n\n::::{.task-container}\n\nRun the code below. Compare the p-value from `t.test()` with the\np-value from `summary(lsmodel1)`. They should be identical.\n\nThis confirms that the intercept-only linear model on paired\ndifferences is the same test as a one-sample t-test. The linear model\nis the more general framework.\n\n::::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(darwin_diff$difference, mu = 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  darwin_diff$difference\nt = 2.148, df = 14, p-value = 0.0497\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 0.003899165 5.229434169\nsample estimates:\nmean of x \n 2.616667 \n```\n\n\n:::\n:::\n\n\n## Composition task: fit the unpaired model {#sec-composition}\n\n:::{.task}\n::::{.task-header}\n**Task: write an `lm()` call for the unpaired comparison**\n::::\n\n::::{.task-container}\n\nYou have just fitted a model that respects the paired design:\n\n```r\nlsmodel1 <- lm(difference ~ 1, data = darwin_diff)\n```\n\nNow write an `lm()` call that ignores the pairing entirely: model\nheight as a function of pollination type, using the original\n`darwin` data frame. Assign the result to `lsmodel2` and run\n`summary()` on it.\n\n\n<div class='webex-solution'><button>Hint</button>\n\nThe response is `height`, the predictor is `type`, and the data are\n`darwin`. The formula takes the form `response ~ predictor`.\n\n</div>\n\n\n\n<div class='webex-solution'><button>Model answer</button>\n\n```r\nlsmodel2 <- lm(height ~ type, data = darwin)\nsummary(lsmodel2)\n```\n\n</div>\n\n\n::::\n:::\n\n:::{.task}\n::::{.task-header}\n**Task: compare the two models**\n::::\n\n::::{.task-container}\n\nLook at the coefficient table for `lsmodel2`.\n\nWhat does the `typeSelf` coefficient estimate? Is this the same\nquantity as the intercept of `lsmodel1`?\n\n\n\n<div class='webex-solution'><button>Answer</button>\n\n\nThe `typeSelf` coefficient estimates the difference in mean height\n   between self-pollinated and cross-pollinated plants — the same\n   quantity as the intercept of `lsmodel1`, but with the opposite\n   sign (Self minus Cross rather than Cross minus Self). The absolute\n   value is the same.\n\n\n</div>\n\n\n::::\n:::\n\n::: {.callout-note}\n## Why pairing matters\nDarwin paired his plants by parent because genetic lineage might play a large role in natural variance in height. By computing the difference *within each pair*, the paired\nanalysis minimises this source of variation and isolates the effect of\npollination type. The unpaired analysis ignores this structure. The lesson: a model should respect the design that\ngenerated the data.\n:::\n\n## Exit ticket {#sec-exit}\n\n:::{.task}\n::::{.task-header}\n**Task: exit question**\n::::\n\n::::{.task-container}\n\nWrite your answer on paper before you leave. This question is\ndeliberately unanswerable from today's material alone — we will\npick this up next time.\n\n> You receive a collaborator's spreadsheet to analyse. The \"species\"\n> column contains entries recorded as \"Drosophila\", \"drosophila\",\n> \"D. melanogaster\", and \"Dros.\". You fit\n> `lm(wing_length ~ species, data = df)` and get four coefficients\n> for species (plus the intercept). Is the model answering the\n> question you intended, and what should you do before fitting it?\n\n::::\n:::\n\n## Reading\n\n### Library\n\n- The New Statistics with R, 2nd Edition, **Chapter 6** by Andy Hector\n\n\n### Online\n\n- [Everything is a Linear Model] (danielroelfs.com/posts/everything-is-a-linear-model/), by Daniel Roelfs\n\n- [Common statistical tests are linear models](lindeloev.github.io/tests-as-linear/), by Jonas Kristoffer Lindeløv - *Covers more than we got to today*\n",
    "supporting": [
      "session-04-computation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}